### PR TITLE
Add opt-in anyobject_protocol rule

### PR DESCRIPTION
**Pull request by ornithocoder**
This commit implements #2283.

### CODE REVIEW

**Comment by ornithocoder** [comment]
@marcelofabri @norio-nomura hi there! Do you have any idea why the linux tests are failing?

**Comment by marcelofabri** [comment]
@ornithocoder I think I remember something like that when implementing `ClassDelegateProtocolRule`. Maybe there's something useful there.

**Comment by marcelofabri** [comment]
BTW, I'm not 100% convinced this should be a default rule. The number of existing violations is an indication of that.

**Comment by ornithocoder** [comment]
@marcelofabri, I'll take a look on the `ClassDelegateProtocolRule`. Thanks.

The Swift documentation [says](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID281) AnyObject should be used to limit protocol adoption to class types. But I'll change it to opt-in.

**Comment by ornithocoder** [comment]
I'll need more time to investigate the Linux issue. Even the very [first implementation](https://github.com/ornithocoder/personal-fork-swiftlint/blob/01dc00f576237571a0140162fdf597def70f02a7/Source/SwiftLintFramework/Rules/AnyObjectProtocolRule.swift) (which simply checks the `inheritedTypes`) was failing on Linux.

**Comment by ornithocoder** [comment]
🧐

I removed everything from the rule, including the violations. This is what happens where I comment out the triggering examples:

without examples

And this is what happens with the triggering examples:

with examples

cc: @marcelofabri @norio-nomura

**Comment by ornithocoder** [comment]
It's ready for review :-)

**Pull request merged**
