### PR TITLE
Do not overwrite files whose contents have not changed

### PR DESCRIPTION
**Pull request by neilgall**
Fixes https://github.com/realm/SwiftLint/issues/574

### CODE REVIEW

**Comment by norio-nomura** [comment]
Nice!
Could you please add changelog entry? [CONTRIBUTING.md](https://github.com/realm/SwiftLint/blob/master/CONTRIBUTING.md#tracking-changes)

**Comment by jpsim** [comment]
Thanks for the PR! This check is fine, but really we shouldn't be generating an empty correction in the first place. Can you please share which situations generate these false corrections? These could be opened as new issues. Thanks!

**Comment by neilgall** [comment]
Sorry, I haven't looked into the reasons why empty corrections are generated. I noticed that swiftlint was touching every file in my project causing long Xcode build times, and simply looked for a way to mitigate this.

**Comment by jpsim** [comment]
Is is possible for you to share which situations generate these false corrections? We can then take it from there to fix those, but I'd consider that a bug.

**Comment by neilgall** [comment]
It seems that any situation generates a false correction. I created an new iOS project in Xcode, corrected the whitespace so swift-lint finds zero violations, then ran `swiftlint autocorrect` with no `.swiftlint.yml` configuration file. The .swift files in the project are overwritten with identical contents.

I haven't looked into the code in depth, but there seems to be a mismatch between the intent of `Linter.correct()` and  `OpeningBraceRule.correctFile()`. `correct()` builds up a list of corrections and invalidates the file's cache if non-empty. `OpeningBraceRule.correctFile()` always invokes `file.write()` via its `writeToFile(_: violatingRanges:)` method, before returning the list of corrections. I suspect the problem lies in OpeningBraceRule.

**Comment by jpsim** [comment]
Ok, thanks for looking into this, and for the PR!

**Pull request merged**
