### PR TITLE
Add XCTestCase examples to unused declaration rule

### PR DESCRIPTION
**Pull request by keith**
This rule correctly handles subclasses of XCTestCase being used, this adds some tests validating this behavior.

### CODE REVIEW

**Comment by jpsim** [comment]
I'd like to teach the tests to link XCTest so we can write tests for this and the direct `XCTestCase` subclass behavior.

**Comment by keith** [comment]
Would that mean collecting the inheritance tree across the entire analyze and walking up it?

**Comment by jpsim** [comment]
I had something much less exciting in mind, the ability to specify additional compiler arguments in `Example`s.

**Comment by keith** [comment]
I'm not sure exactly what you mean here, but I'm open to going down that path if you'd like!

**Comment by keith** [comment]
Still relevant

**Comment by jpsim** [comment]
I think the only thing missing here is tests.

**Comment by keith** [comment]
Happy to add some, since it requires custom configuration should I write them in a separate custom test function?

**Comment by jpsim** [comment]
I'm sorry I wasn't communicating clearly what I had in mind. Sometimes the best way to communicate is with code so I pushed up what I meant:

* Teach the test helpers how to find the XCTest framework: aa8b4bf
* Teach the `violations(...)` test helper to apply the configuration from Examples: fb9b00b

**Comment by keith** [comment]
Updated this PR to just add test cases for this behavior since it was fixed with the switch to indexing!

**Pull request merged**
