### PR TITLE
Add `legacy_objc_type` Opt In Rule

### PR DESCRIPTION
**Pull request by 72A12F4E**
This change implements #2758

I was getting some unexpected behavior when I tried using SwiftLintFile.match(pattern:with:range:) to match the expected areas of code that I wanted, so I just filtered the matches manually.

I expected SwiftLintFile.match(pattern:with:range:) to return if any of the SyntaxKinds in the array I passed in were a match, but in the implementation its checking to see if the parameter has a match on every SyntaxKind passed in. It's like an AND instead of an OR?

New to the codebase, so I'm not sure if there is a better method for doing what I wanted.

### CODE REVIEW

**Comment by 72A12F4E** [comment]
I was getting some unexpected behavior when I tried using `SwiftLintFile.match(pattern:with:range:)` to match the expected areas of code that I wanted, so I just filtered the matches manually. New to the codebase, so I'm not sure if there is a better method for doing what I wanted

**Comment by 72A12F4E** [comment]
Also, I seem to be getting a ton of CI build errors unrelated to my changes where SourceKittenFramework doesn't look like its being imported even though it is. 

Is this an existing problem?

**Comment by 72A12F4E** [comment]
@jpsim I think I have this to a place where I am comfortable with it. Can you take a quick pass and let me know if there is anything I could improve?

**Comment by jpsim** [comment]
Sorry for the long delay, this looks good, I've revived in https://github.com/realm/SwiftLint/pull/3531 and will merge when CI passes.

**Comment by 72A12F4E** [comment]
Thanks so much JP! I'm really glad this finally made it! 😄 Keep up the great work on SwiftLint!

**Pull request closed without merging**
