### PR TITLE
add --lenient

### PR DESCRIPTION
**Pull request by aaroncrespo**

### CODE REVIEW

**Comment by aaroncrespo** [comment]
Don't worry about un-verified I did this on a computer missing my gpg. key.

**Comment by aaroncrespo** [comment]
re: #1322

**Comment by aaroncrespo** [comment]
CI Is failing because type checking something took 190ms over the 150ms max.

**Comment by aaroncrespo** [comment]
Not sure what to do next the failures seem unrelated to the changes in this PR.

**Comment by marcelofabri** [comment]
I think the issue was more about using warnings (and never errors) than the return code.

**Comment by aaroncrespo** [comment]
I've updated the PR:
* convert any error violations to warning violations. I couldn't see an approach that was much different than what I did outside of parameterizing the option to all sorts of types.
* then if lenient is set, I suppress any warning threshold error

**Comment by marcelofabri** [comment]
Integrations tests are failing, can you please take a look at this?

**Comment by aaroncrespo** [comment]
going to resubmit I think a squash failed.

**Pull request closed without merging**
