### PR TITLE
Fix ValidDocs rule

### LINKED ISSUE #375: Valid docs rule not covering all closure parameter cases.
I've noticed that some cases are not being covered by the `validDocsRule` and SwiftLint generates wrong warnings, for instance:
* `func foobar (closure1: () -> Foo, closure2: (foobar: Bar) -> Foo, closure3: (foobar: Bar) -> Foo) {`
* `func footer (closure1: (Foo) -> Void, onError closure2: ((NSError) -> Void)? = nil) {`

I'll add a pull request with a fix for this ASAP.

### PR DESCRIPTION
**Pull request by diogoguimaraes**
Closes #375 .

### CODE REVIEW

**Comment by diogoguimaraes** [comment]
@jpsim can you help me with the `codecov` please?

**Comment by jpsim** [comment]
Thanks for this! The code coverage isn't significantly affected so that's fine, but this code is kind of duplicated at this point, so it'd be good to combine, which would also incidentally help code coverage.

Nice work!

**Comment by diogoguimaraes** [comment]
Thanks! 
Do you think we should do this before merging this PR?
Regarding the "combine" could you be more specific?

**Comment by jpsim** [comment]
I made a few minor changes: combining some duplicate code and adding a changelog entry. This will be good to go once it passes CI.

Thanks again!

**Comment by diogoguimaraes** [comment]
Thanks again!
Do you have an ETA to the next release?

**Comment by jpsim** [comment]
0.7.0 was accepted into Homebrew yesterday: https://github.com/Homebrew/homebrew/pull/48425#issuecomment-174798049

Do you need the fix from this PR in a release? If so, I could push out a 0.7.1 release today, although I can't say when Homebrew will accept it. The last few submissions each took a few days.

**Comment by diogoguimaraes** [comment]
That would be great! Thank you.

**Comment by jpsim** [comment]
0.7.1 has been cut: https://github.com/realm/SwiftLint/releases/tag/0.7.1

and submitted to homebrew: https://github.com/Homebrew/homebrew/pull/48497

**Pull request merged**
