### PR TITLE
Add multiline closure argument rule

### PR DESCRIPTION
**Pull request by keith**
This rule forces users to name arguments for multiline closures.

This is the first draft of https://github.com/realm/SwiftLint/issues/70

See the first commit for the rule. The second is just fixes for it.

### CODE REVIEW

**Comment by segiddins** [comment]
if at all possible, it might be preferable to make this single statement closures instead of single-line

**Comment by jpsim** [comment]
Lol, of course the rule would violate itself:

```
/Users/travis/build/realm/SwiftLint/Source/SwiftLintFramework/Rules/MultilineClosureArgumentRule.swift:14:32: error: Force Try Violation: Force tries should be avoided. (force_try)
/Users/travis/build/realm/SwiftLint/Source/SwiftLintFramework/Rules/MultilineClosureArgumentRule.swift:25:1: warning: Multi-line closure argument Violation: Multi-line closures should not use $0 (closure_argument)
/Users/travis/build/realm/SwiftLint/Source/SwiftLintFramework/Rules/MultilineClosureArgumentRule.swift:32:1: warning: Multi-line closure argument Violation: Multi-line closures should not use $0 (closure_argument)
/Users/travis/build/realm/SwiftLint/Source/SwiftLintFramework/Rules/MultilineClosureArgumentRule.swift:41:1: warning: Multi-line closure argument Violation: Multi-line closures should not use $0 (closure_argument)
/Users/travis/build/realm/SwiftLint/Source/SwiftLintFramework/Rules/MultilineClosureArgumentRule.swift:42:1: warning: Multi-line closure argument Violation: Multi-line closures should not use $0 (closure_argument)
```

**Comment by keith** [comment]
Yea I can disable those if we want to move forward with this. And fix the description.

**Comment by jpsim** [comment]
I think we have a difference of stylistic opinion regarding when it's appropriate to use `$0`.

I'd be much more inclined to say it's for single *statements* like @segiddins suggested rather than requiring the closure's braces to be on the same line.

I actually consider all of SwiftLint's current uses of the dollar sign shorthand to be appropriate in that sense.

Unfortunately, I have no idea how to detect statements.

**Comment by jpsim** [comment]
By the way, it'd be trivial to update this rule to only apply in the appropriate context:

```diff
-    private static let regex = try! NSRegularExpression(pattern:
-        "(^[^\\{\\n]*\\$0|\\$0[^\\}\\n]*$)", options: .AnchorsMatchLines)
-
     public func validateFile(file: File) -> [StyleViolation] {
-        let range = NSRange(location: 0, length: file.contents.utf16.count)
-        let matches = MultilineClosureArgumentRule.regex.matchesInString(file.contents,
-            options: [], range: range)
-
-        return matches.map { match in
-            return StyleViolation(ruleDescription: self.dynamicType.description,
-                location: Location(file: file, offset: match.range.location))
+        let pattern = "(^[^\\{\\n]*(\\$0)|(\\$0)[^\\}\\n]*$)"
+        return file.matchPattern(pattern, withSyntaxKinds: [.Identifier]).map { match in
+            StyleViolation(ruleDescription: self.dynamicType.description,
+                           location: Location(file: file, offset: match.location))
         }
     }
```

**Comment by jpsim** [comment]
@keith would you like to revive this now that we have opt-in rules?

**Comment by keith** [comment]
Sure. I'll try and get to the feedback shortly.

**Comment by jpsim** [comment]
FWIW I wouldn't enable it for this project.

**Comment by scottrhoyt** [comment]
@keith do you have any updates here? Or should we close this PR out?

**Comment by keith** [comment]
I'll reopen this when I have time to make the fixes!

**Comment by jpsim** [comment]
I'll actually take a stab at reviving this if you don't mind @keith. I think it's a great rule to have, even on by default, but keeping the default number of lines a bit higher (4-5?).

**Comment by keith** [comment]
Have at it! I think that a single line is a nice rule, but maybe that could be customizable?

**Comment by jpsim** [comment]
> Have at it! I think that a single line is a nice rule, but maybe that could be customizable?

Yeah, if this goes in, it should certainly be customizable.

**Comment by jpsim** [comment]
Hmm, on second thought, I don't think I can do this as easily as I had expected... There's no `SwiftDeclarationKind` for closures, so they're a bit hard to detect.

**Pull request closed without merging**
