### PR TITLE
Mark Swift 5 as supported

### PR DESCRIPTION
**Pull request by jpsim**

### CODE REVIEW

**Comment by jpsim** [comment]
Needs https://github.com/jpsim/SourceKitten/pull/588

**Comment by jpsim** [comment]
`testSimulateHomebrewTest` is flaky, going to ignore.

**Comment by norio-nomura** [comment]
> `testSimulateHomebrewTest` is flaky, going to ignore.

Apparently there seems to be an unknown condition that SourceKit will not crash even with sandbox. :thinking:
It seems better to remove `testSimulateHomebrewTest`. To confirm that sandbox crash avoidance works, leaving `testSimulateHomebrewTestWithDisableSourceKit` is sufficient.

**Comment by norio-nomura** [comment]
I'll open a PR that makes `testSimulateHomebrewTest` as opt-in test by environment variable.

**Pull request merged**
