### PR TITLE
Warn when disabling non existing rules

### PR DESCRIPTION
**Pull request by kimdv**
Hi! 

I tried to solve #2348

Pleaese let me now if i'm on the correct path 🕺

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for starting on this! I think this needs to consider custom rules, which can be disabled but don't map to a valid rule identifier. Maybe the right way to do this would be to include custom rule IDs in `RuleList.allValidIdentifiers()`.

It seems like OSSCheck caught false positives for `natural_text_alignment` and `inverse_text_alignment` in WordPress.

I also have two small patches when I was looking at this locally. Feel free to apply whatever subset you think is best:

<details>
<summary>Patch</summary>

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 348d97e9..d2433de5 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -29,10 +29,10 @@
   [Kim de Vos](https://github.com/kimdv)
   [#2108](https://github.com/realm/SwiftLint/issues/2108)
 
-* Improved `superfluous_disable_command` to warn against disabling non valid
+* Improve `superfluous_disable_command` to warn against disabling undefined
   rules.  
   [Kim de Vos](https://github.com/kimdv)
-  [#2108](https://github.com/realm/SwiftLint/issues/2108)
+  [#2348](https://github.com/realm/SwiftLint/issues/2348)
 
 #### Bug Fixes
 
diff --git a/Source/SwiftLintFramework/Models/Linter.swift b/Source/SwiftLintFramework/Models/Linter.swift
index f08833e6..55378204 100644
--- a/Source/SwiftLintFramework/Models/Linter.swift
+++ b/Source/SwiftLintFramework/Models/Linter.swift
@@ -80,7 +80,7 @@ private extension Rule {
             allViolations: violations
         )
 
-        let nonValidSuperfluousCommandViolations = self.nonValidSuperfluousCommandViolations(
+        let undefinedDisableCommandViolations = self.undefinedSuperfluousCommandViolations(
             regions: regions,
             superfluousDisableCommandRule: superfluousDisableCommandRule)
 
@@ -98,28 +98,28 @@ private extension Rule {
             return identifiers.map { ($0, ruleID) }
         }
 
-        return LintResult(violations: enabledViolations + superfluousDisableCommandViolations +
-            nonValidSuperfluousCommandViolations,
-                          ruleTime: ruleTime,
-                          deprecatedToValidIDPairs: deprecatedToValidIDPairs)
+        return LintResult(
+            violations: enabledViolations + superfluousDisableCommandViolations + undefinedDisableCommandViolations,
+            ruleTime: ruleTime,
+            deprecatedToValidIDPairs: deprecatedToValidIDPairs
+        )
     }
 
-    private func nonValidSuperfluousCommandViolations(regions: [Region],
-                                                      superfluousDisableCommandRule: SuperfluousDisableCommandRule?
+    private func undefinedSuperfluousCommandViolations(regions: [Region],
+                                                       superfluousDisableCommandRule: SuperfluousDisableCommandRule?
         ) -> [StyleViolation] {
-        let allValidIdentifiers = Set(masterRuleList.allValidIdentifiers().map { RuleIdentifier($0) })
-
         guard !regions.isEmpty, let superfluousDisableCommandRule = superfluousDisableCommandRule else {
             return []
         }
 
+        let allValidIdentifiers = Set(masterRuleList.allValidIdentifiers().map { RuleIdentifier($0) })
         let regions = regions.filter {
             !$0.disabledRuleIdentifiers.contains(.all) &&
                 $0.disabledRuleIdentifiers.isDisjoint(with: allValidIdentifiers)
         }
 
         return regions.compactMap { region in
-            for id in region.disabledRuleIdentifiers where !allValidIdentifiers.contains(id) {
+            return region.disabledRuleIdentifiers.first(where: { !allValidIdentifiers.contains($0) }).map { id in
                 return StyleViolation(
                     ruleDescription: type(of: superfluousDisableCommandRule).description,
                     severity: superfluousDisableCommandRule.configuration.severity,
@@ -127,8 +127,6 @@ private extension Rule {
                     reason: superfluousDisableCommandRule.reason(for: id.stringRepresentation)
                 )
             }
-
-            return nil
         }
     }
 }
```

</details>

**Comment by jpsim** [comment]
> Merge branch 'master' into kimdv/non-valid-rules

This will fail Danger since we have a check to avoid merge commits in PRs. Can you rebase instead?

**Comment by kimdv** [comment]
@jpsim I will see if I can figure out to rebase 👍

**Comment by jpsim** [comment]
> I'm a bit stuck on how to add custom rules ids to `RuleList.allValidIdentifiers()`.
I can't see how I can access the configured rule.

I think we might need to add the ability to get custom rule identifiers out of a Configuration. Then we could do `RuleList.allValidIdentifiers() + configuration.customRuleIdentifiers`.

> And is my rebase correct. It seems a bit messy?

It’s okay. Something I do is amend commits with their merge fixes before pushing up the rebased branch to keep it clean. You don’t have to do this though, but it’s not a bad fit technique to learn. Up to you.

**Comment by kimdv** [comment]
> > I'm a bit stuck on how to add custom rules ids to `RuleList.allValidIdentifiers()`.
> > I can't see how I can access the configured rule.
> 
> I think we might need to add the ability to get custom rule identifiers out of a Configuration. Then we could do `RuleList.allValidIdentifiers() + configuration.customRuleIdentifiers`.
> 
``` swift
 func lint(file: File, regions: [Region], benchmark: Bool,
              configuration: Configuration,
              superfluousDisableCommandRule: SuperfluousDisableCommandRule?,
              compilerArguments: [String]) -> LintResult?
```
Is this something you had in your mind?
Pass the configuration, and then pass it to the 

``` swift
private func undefinedSuperfluousCommandViolations(regions: [Region], configuration: Configuration,
                                                       superfluousDisableCommandRule: SuperfluousDisableCommandRule?
        ) -> [StyleViolation]
```

**Comment by jpsim** [comment]
Sorry for the delay. I suggest you do what you think is best, since you're more familiar with what you're trying to accomplish and what's blocking you, and in code review myself or other maintainers may be able to find improvements, if any are lurking around the corner 😉

**Comment by kimdv** [comment]
@jpsim I have made it work now, I think 😀
I have disabled one rule, I'm not proud of it! So feel free to come with suggestions!

**Pull request merged**
