### PR TITLE
Add "Redundant @objc Attribute" Rule

### PR DESCRIPTION
**Pull request by dirtydanee**
Implements https://github.com/realm/SwiftLint/issues/2193

### CODE REVIEW

**Comment by jpsim** [comment]
I'm sorry for the long delay in reviewing this. Would you mind rebasing and pinging me again to review? Thanks for the PR!

**Comment by dirtydanee** [comment]
@jpsim rebased to latest master

**Comment by jpsim** [comment]
Looks good! I can see a lot of care went into this, so thank you for that! I made a few refactors, I hope you don't mind. Assuming CI is happy with this, we can merge 😄

**Comment by Kaspik** [comment]
Thanks for doing this guys!! But there is an issue with selectors. Imagine code:
`button.addTarget(self, action: #selector(getPrintablePosterButtonAction), for: UIControl.Event.touchUpInside)`
This requires to have method with @objc selector - `@objc private func getPrintablePosterButtonAction() {}`. Now if it's inside @objcMembers class, this causes warnings.

I know I can suppress them, but I was thinking if there is not any workarounds or checks for these cases. :)

**Comment by jpsim** [comment]
Sounds like that might be a Swift bug actually. Functions that are representable by the objective-c runtime that are encased in an `@objcMembers` class should be automatically treated as `@objc` themselves.

**Comment by dirtydanee** [comment]
I have run a quick test, and the issue seem to be only occurring, if the function is marked as `private`.

I should have some time to look into this week, will update this thread with my findings.

**Comment by jpsim** [comment]
> I have run a quick test, and the issue seem to be only occurring, if the function is marked as `private`.
> 
> I should have some time to look into this week, will update this thread with my findings.

This seems correct, and probably isn't a Swift bug, but rather subtle behavior with `@objcMembers`, where it isn't automatically applied to private members. It should be easy to special case this in the rule.

**Comment by Kaspik** [comment]
Thank you guys, sorry for bringing up these problems, ideal would be to remove `@objcMemebers` from our app but we can't sometimes. 😄

**Comment by jpsim** [comment]
Not at all, we shouldn't change our code just to satisfy linters 😀

**Pull request merged**
