### PR TITLE
Allow newlines in function return arrow

### PR DESCRIPTION
**Pull request by jpsim**
This prevented SwiftLint from linting as of #118. /cc @keith

### CODE REVIEW

**Comment by keith** [comment]
Oops! Sorry about that, shouldn't CI have failed for that PR?

**Comment by keith** [comment]
:+1:

**Comment by jpsim** [comment]
> shouldn't CI have failed for that PR?

Yeah, I'm also weirded out as to why the integration tests didn't fail: https://travis-ci.org/realm/SwiftLint/builds/78498728#L2679

**Comment by jpsim** [comment]
hmmm, I don't know why this is failing on travis, it's passing for me locally...

**Comment by keith** [comment]
I'm seeing this failing locally, it looks like `func abc()  ->  Int {}\n` is the failing example.

**Comment by keith** [comment]
I'm not sure what `\h` is but just reverting your regex change and adding those 2 examples passes for me locally `¯\_(ツ)_/¯`

**Comment by jpsim** [comment]
`\h` is horizontal spacing, but is a fairly recent addition to regex syntax. I'll revert that part.

**Comment by jpsim** [comment]
I think I sort of figured this weirdness out... Depending on the system, `\v` matches `\n`, while `\h` may or may not be supported.

**Pull request merged**
