### PR TITLE
Avoid withoutTrivia() where it’s not necessary

### PR DESCRIPTION
**Pull request by marcelofabri**

### CODE REVIEW

**Comment by marcelofabri** [comment]
it's interesting that the violations seem to be valid, but not sure why this change would start flagging them

**Comment by jpsim** [comment]
Have you figured out the OSSCheck results?

**Comment by marcelofabri** [comment]
> Have you figured out the OSSCheck results?

Not really, my best guess is that there's something about these files that perhaps trigger a bug in SwiftSyntax when calling `withoutTrivia()`?

**Comment by SimplyDanny** [comment]
All changes are contained in 2f0e537.

**Pull request closed without merging**
