### PR TITLE
Option to ignore one or all rules for a file by adding a comment

### PR DESCRIPTION
**Pull request by evermeer**
With this change you can disable all rules for a file by adding the following line to your swift file:
// SwiftLint ignore all
or you can disable a specific rule by adding something like:
// SwiftLint ignore variable_name
Where variable_name is the identifier of the rule

### CODE REVIEW

**Comment by segiddins** [comment]
This only seems to be per-file, and thus has no way to only ignore a certain section of code?

**Comment by jpsim** [comment]
This would conflict with the current proposal described in #4. Although the approach of filtering the results could still work with file regions rather than per-file.

**Comment by evermeer** [comment]
When #4 will be implemented soon, then this PR can be closed without merge.

**Comment by keith** [comment]
A similar but different version of this was implemented in https://github.com/realm/SwiftLint/pull/111

**Comment by jpsim** [comment]
Thanks for pointing that out, @keith. Closing since #111 allows this behavior and more.

**Pull request closed without merging**
