### PR TITLE
Generalize TodoRule

### PR DESCRIPTION
**Pull request by jpsim**
as prompted by my own recommendations... doh! https://github.com/realm/SwiftLint/pull/126#issuecomment-137846688

### CODE REVIEW

**Comment by keith** [comment]
Hadn't submitted a PR for this yet but this also doesn't cover the Google `TODO(keith):` version.

**Comment by jpsim** [comment]
How about we relax this rule even more to just be `\b(TODO|FIXME)\b` limited to comments?

**Comment by keith** [comment]
:+1:

**Comment by keith** [comment]
Looks good :+1:

**Pull request merged**
