### PR TITLE
Use prefix(while:) instead of partioned

### PR DESCRIPTION
**Pull request by marcelofabri**
Since we don't run tests on Swift 3.0.x anymore

### CODE REVIEW

**Comment by jpsim** [comment]
If we deprecate Swift 3.0.x, we should list it in the changelog, readme and we'll need to bump up the  homebrew formula requirements.

**Comment by marcelofabri** [comment]
> we'll need to bump up the homebrew formula requirements.

that's something that should be done when submitting the next version, right?

**Comment by jpsim** [comment]
It would, but I don't think it's worth deprecating Swift 3.0 for this.

**Comment by marcelofabri** [comment]
Fair enough,

**Comment by marcelofabri** [comment]
Actually, I'm not sure. Since we don't test building on Swift 3.0.x anymore, maybe we'll accidentally break this in the future any way.

Also, this shouldn't matter for most people, I'd assume (since they don't build from source).

**Comment by jpsim** [comment]
🎉

**Pull request merged**
