### PR TITLE
Remove support for building with Swift 3.1

### PR DESCRIPTION
**Pull request by marcelofabri**

### CODE REVIEW

**Comment by jpsim** [comment]
```
$ rm Package.swift
$ git mv Package@swift-4.swift Package.swift
```

**Comment by jpsim** [comment]
It'd be nice to test on Swift 3.2 as well.

**Comment by jpsim** [comment]
> It'd be nice to test on Swift 3.2 as well.

Nevermind, I guess we're already testing this with `xcodebuild` since the Xcode project still has `SWIFT_VERSION = 3`.

**Comment by jpsim** [comment]
I hope you don't mind, I made some changes & addressed merge conflicts and pushed to your branch.

**Comment by marcelofabri** [comment]
Not really, thanks for continuing this 💯

**Comment by jpsim** [comment]
All CI jobs passed locally, not waiting on Travis.

**Pull request merged**
