### PR TITLE
enable explicit_top_level_acl  and extension_access_modifier

### PR DESCRIPTION
**Pull request by masters3d**
In order to reach the consistency goals of https://github.com/realm/SwiftLint/pull/1543 ;

This PR seeks to Enable :
* `explicit_top_level_acl` 
* `extension_access_modifier`

Complementary PR to the above goals https://github.com/realm/SwiftLint/pull/1489 
* `fileprivate`

### CODE REVIEW

**Comment by masters3d** [comment]
@jpsim Circle has been failing for multiple PR. Do you mind checking it out? Thanks!

**Comment by marcelofabri** [comment]
@masters3d sorry for the delay. Would you mind splitting this into two PRs (one for each rule)?

I agree with enabling `extension_access_modifier`, but I'd like to discuss more about `explicit_top_level_acl`. In short, I don't think it makes sense to enable it on the unit tests.

**Comment by masters3d** [comment]
What are you thinking? Adding a case for XCTestCase exception as an option in the config?

**Comment by marcelofabri** [comment]
> What are you thinking? Adding a case for XCTestCase exception as an option in the config?

No, I think the proper way to solve this is with nested configurations.

**Comment by masters3d** [comment]
Nested configs require duplicating the config file, correct?
https://github.com/realm/SwiftLint/issues/676
Is that what you are proposing here?

**Pull request closed without merging**
