### PR TITLE
add experimental rules for Firebase SDK compatibility

### PR DESCRIPTION
**Pull request by iulukaya**

### CODE REVIEW

**Comment by marcelofabri** [comment]
This definitely should be an opt-in rule. Also, the headers are not in the project's format (unit tests will fail)

**Comment by iulukaya** [comment]
Thanks Marcelo, I'll definitely make them opt-in rule, and fix the headers

**Comment by iulukaya** [comment]
Hi Marcelo, I realized unit tests forces every file to have Copyright @ xxxx Realm.
As I want to add these rules on behalf of Firebase(Google) that would make it complicated.
Can we have a AUTHORS file that add Google Inc. and Realm
at the root of the repository.

**Comment by marcelofabri** [comment]
I'll leave it for @jpsim

**Comment by jpsim** [comment]
I appreciate the contributions @iulukaya, but I'd like to see these rules made a bit more robust before shipping them with SwiftLint. For example, it seems like it'd be very easy to have false positives for most of these rules right now, because you're just excluding comments and strings rather than checking the specific kinds of method calls, etc.

It also seems as though most of these rules could be written as custom rules in a `.swiftlint.yml` configuration. Perhaps you'd be interested in contributing the first SwiftLint configuration as described in #517? Such as `examples/swiftlint_firebase.yml`.

**Comment by iulukaya** [comment]
Hi @jpsim , I agree with both statements. Looks like I need to check for a certain "method call" inside a certain "function declaration". I was trying to do it in custom yaml rules, but couldn't find enough docs. Not sure how to match or ignore "declaration of method type", it only allows me to check syntax kind. Or how to "exclude".
Maybe if you can point me to available comments inside custom rules (like a reference guide) or at least the file you read (so I can find all available options), or show me one of the rules as an example, I can go from there.
Cheers,

**Comment by iulukaya** [comment]
@jpsim quick ping on this. (also not sure why that particular test is failing on jazzy. It works fine locally.)

**Comment by iulukaya** [comment]
@marcelofabri wdyt?

**Pull request closed without merging**
