### PR TITLE
Fix overlapping commands causing incorrect Region generation

### LINKED ISSUE #1388: `// swiftlint:disable:this` does not work if it placed on next line to `// swiftlint:disable:next`
Reproducing code:
```swift
// swiftlint:disable:next identifier_name
func ViolatingIdentifierName(){ // swiftlint:disable:this function_body_length opening_brace
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("10")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("20")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("30")
    print("1")
    print("2")
    print("3")
    print("4")
    print("5")
    print("6")
    print("7")
    print("8")
    print("9")
    print("40")
    print("1")
}
```
`function_body_length` and `opening_brace` are detected:
```terminal.session
swiftlint lint --enable-all-rules --path test.swift
Linting Swift files at path test.swift
Linting 'test.swift' (1/1)
Valid Docs rule is disabled in Swift 2.3 and later as it is non functional.
Missing Docs rule is disabled in Swift 2.3 and later as it is non functional.
/…/swiftlint-test/test.swift:2:1: warning: Function Body Length Violation: Function body should span 40 lines or less excluding comments and whitespace: currently spans 41 lines (function_body_length)
/…/swiftlint-test/test.swift:2:30: warning: Opening Brace Spacing Violation: Opening braces should be preceded by a single space and on the same line as the declaration. (opening_brace)
Done linting! Found 2 violations, 0 serious in 1 file.
```

### PR DESCRIPTION
**Pull request by jpsim**
fixes #1388.

### CODE REVIEW

**Comment by marcelofabri** [comment]
@jpsim Are the results from oss-check reliable in this case? 😬

**Comment by marcelofabri** [comment]
Also maybe we should have a test for this?

**Comment by jpsim** [comment]
Yes this needs a test. I'll also do a local run of osscheck to measure performance impact and we'll see another run on CI when I push the test up.

**Comment by jpsim** [comment]
I added many tests to Command/Action/Region that were never really directly tested, only indirectly via integration or rule tests. I just ran OSSCheck locally and the perf numbers look good, with essentially no impact, which is what I'd expect:

```
Linting Aerial with this PR took 0.25s vs 0.26s on master (3% faster)
Linting Alamofire with this PR took 1.72s vs 1.76s on master (2% faster)
Linting Firefox with this PR took 7.29s vs 7.4s on master (1% faster)
Linting Kickstarter with this PR took 9.93s vs 9.69s on master (2% slower)
Linting Moya with this PR took 0.23s vs 0.25s on master (7% faster)
Linting Nimble with this PR took 0.94s vs 0.96s on master (2% faster)
Linting Quick with this PR took 0.32s vs 0.33s on master (3% faster)
Linting Realm with this PR took 1.57s vs 1.55s on master (1% slower)
Linting SourceKitten with this PR took 0.64s vs 0.64s on master (0% slower)
Linting Sourcery with this PR took 1.66s vs 1.65s on master (0% slower)
Linting Swift with this PR took 7.51s vs 7.44s on master (0% slower)
Linting WordPress with this PR took 7.28s vs 7.27s on master (0% slower)
```

**Comment by norio-nomura** [comment]
Thanks for fix! 🙏

**Pull request merged**
