### PR TITLE
Add ../Frameworks to RPATH

### PR DESCRIPTION
**Pull request by S2dentik**
* This is used for when running the binary from inside the
swiftlint.app package.

### CODE REVIEW

**Comment by norio-nomura** [comment]
We don't accept this change, because this introduces the issue that loading `SourceKittenFramework` installed by `sourcekitten` instead of `SourceKittenFramework` installed by `swiftlint`.
I confirmed that by `make install` with this change:
```terminal.sh-session
➜  8:40:46 git:(pr/1624) lldb swiftlint
swift_oss_helper command enabled.
(lldb) target create "swiftlint"
Current executable set to 'swiftlint' (x86_64).
(lldb) image list -s
[  0] /usr/local/bin/swiftlint
[  1] /usr/lib/dyld
[  2] /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
[  3] /usr/lib/libobjc.A.dylib
[  4] /usr/lib/libSystem.B.dylib
[  5] /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
[  6] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/Commandant.framework/Commandant
[  7] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
[  8] /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
[  9] /usr/local/Frameworks//SourceKittenFramework.framework/SourceKittenFramework
[ 10] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/SwiftyTextTable.framework/Versions/A/SwiftyTextTable
[ 11] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftCore.dylib
[ 12] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftCoreGraphics.dylib
[ 13] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftDarwin.dylib
[ 14] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftDispatch.dylib
[ 15] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftFoundation.dylib
[ 16] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftIOKit.dylib
[ 17] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftObjectiveC.dylib
…
```

**Comment by S2dentik** [comment]
@norio-nomura, good catch, it actually depends on the ordering, I've changed this to be the last in the order of `@rpath`s, thus falling to this if all the others fail, tested on my side, nothing seems to change between master and this when using your steps.
```
(lldb) image list -s
[  0] /usr/local/bin/swiftlint
[  1] /usr/lib/dyld
[  2] /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
[  3] /usr/lib/libobjc.A.dylib
[  4] /usr/lib/libSystem.B.dylib
[  5] /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
[  6] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/Commandant.framework/Commandant
[  7] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
[  8] /Library/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
[  9] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/SourceKittenFramework.framework/SourceKittenFramework
[ 10] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/SwiftyTextTable.framework/Versions/A/SwiftyTextTable
[ 11] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftCore.dylib
[ 12] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftCoreGraphics.dylib
[ 13] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftDarwin.dylib
[ 14] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftDispatch.dylib
[ 15] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftFoundation.dylib
[ 16] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftIOKit.dylib
[ 17] /Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks/libswiftObjectiveC.dylib
```

**Comment by norio-nomura** [comment]
`SwiftLint.pkg` installs `/Library/Frameworks/SwiftLintFramework.framework`. Even if you changed the order in `rpath`, `swiftlint.app` may use `/Library/Frameworks/SwiftLintFramework.framework` instead of the bundled version.
Therefore, I think that using `swiftlint.app` other than debugging under Xcode is not recommended.

What kind of usage is assumed for this change?

**Comment by S2dentik** [comment]
It was the first and most trivial usage I stumbled into: made some changes to the project, built `swiftlint` target, opened `swiftlint.app` inside `Products`, and the binary lying inside, and stumbled into the error that `SourceKitten.framework` isn't found in the @rpath

**Comment by norio-nomura** [comment]
Perhaps it is fortunate that it is an error not to be an error. If it does not get an error, `swiftlint.app` will run lint from` / `. 😜

**Comment by S2dentik** [comment]
Well, the default behavior doesn't really change. The only thing that changes is that if `swiftlint` doesn't find all the necessary libraries in the previous paths, it will have one more to look into. I don't think it might break anything, but you should be more aware of some edge-cases 🙈

**Comment by norio-nomura** [comment]
I will write about `rpath` of swiftlint as it is a good opportunity.

---
We distribute `swiftlint` in three methods.
- `SwiftLint.pkg`
- Homebrew
- `portable_swiftlint.zip`

`LC_RPATH` entries of `swiftlint` are configured in `Makefile` for supporting each distribution methods.

### `SwiftLint.pkg`
Is created by `make package`, installed by `make install`.
Installed locations:
```
/usr/local/bin/swiftlint
/Library/Frameworks/SwiftLintFramework.framework
```
`swiftlint` has the following `LC_RPATH` entries:
```
/Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks
/Library/Frameworks
```

### Homebrew
is Installed by `make prefix_install PREFIX=/usr/local/Cellar/swiftlint/<version>`.
Installed locations:
```
/usr/local/Cellar/swiftlint/<version>/bin/swiftlint
/usr/local/Cellar/swiftlint/<version>/Frameworks/SwiftLintFramework.framework
```
Those are symbolically linked to:
```terminal.sh-session
$ la /usr/local/bin/swiftlint
lrwxr-xr-x  1 norio  admin    40B  6 15 18:34 /usr/local/bin/swiftlint@ -> ../Cellar/swiftlint/0.19.0/bin/swiftlint
$ la -R /usr/local/Frameworks/SwiftLintFramework.framework
total 16
lrwxr-xr-x  1 norio  admin    79B  6 15 18:34 Resources@ -> ../../Cellar/swiftlint/0.19.0/Frameworks/SwiftLintFramework.framework/Resources
lrwxr-xr-x  1 norio  admin    88B  6 15 18:34 SwiftLintFramework@ -> ../../Cellar/swiftlint/0.19.0/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
drwxr-xr-x  4 norio  admin   136B  6 15 18:34 Versions/

/usr/local/Frameworks/SwiftLintFramework.framework/Versions:
total 16
lrwxr-xr-x  1 norio  admin    83B  6 15 18:34 A@ -> ../../../Cellar/swiftlint/0.19.0/Frameworks/SwiftLintFramework.framework/Versions/A
lrwxr-xr-x  1 norio  admin    89B  6 15 18:34 Current@ -> ../../../Cellar/swiftlint/0.19.0/Frameworks/SwiftLintFramework.framework/Versions/Current
```
`swiftlint` has the following `LC_RPATH` entries:
```
@executable_path/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks
@executable_path/../Frameworks
```

### `portable_swiftlint.zip`
Is created by `make portable_zip`. Used on cocoapods.
`swiftlint` runs in any location if `swiftlint` and `SwiftLintFramework.framework` exist in same directory.
`swiftlint` has the following `LC_RPATH` entries:
```
@executable_path/SwiftLintFramework.framework/Versions/Current/Frameworks
@executable_path
```

**Comment by norio-nomura** [comment]
I am closing this because there is no further reason to need this.

**Pull request closed without merging**
