### PR TITLE
Build with swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a

### PR DESCRIPTION
**Pull request by norio-nomura**
Notes:
- SPM does not use Package.swift in dependencies. So it removes unnecessary directories in `Packages/*` that cause build error.
- Using `--configuration release` crashes compiler.
- Using forked dependencies:

Uses forked dependencies:
- https://github.com/norio-nomura/SourceKitten/  
  Updated Package.swift  
  Added `0.8.1-test` tag for fetching  
- https://github.com/norio-nomura/Commandant/  
  Added `0.8.3-test` tag for fetching  
- https://github.com/norio-nomura/YamlSwift/  
  Added Package.swift  
  Fixed build error on swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a  
  Added `1.4.0-test` tag for fetching

### CODE REVIEW

**Comment by norio-nomura** [comment]
It runs `swift build` twice in `Makefile`
1. On first run of `swift build`, that fails with unnecessary directories in `Packages/*`.
2. Makefile removes unnecessary directories in Packages/* that cause build error.
3. On second run of `swift build`, that success.

**Comment by jpsim** [comment]
Thanks for doing this @norio-nomura! The dual build workaround is certainly unfortunate. I'd rather fix the directory layouts in `SourceKitten` and `Yaml` to fully support SPM.

If you make a PR in SourceKitten, I'll be happy to merge and tag a new version, so we can point to the main repo. It'd be nice if you could make a PR towards YamlSwift with your changes to replace mine since yours is more comprehensive (https://github.com/behrang/YamlSwift/pull/18). But for that repo, it's fine to point to your fork until those changes are merged & tagged in YamlSwift, which might take a while if my open PR is any indication.

So fixing the source layouts in the dependencies will help us avoid the dual build workaround you have here.

**Comment by norio-nomura** [comment]
In that workaround, it removes `Source/sourcekitten`.
If moving that to another place in SourceKitten for avoiding build error in SwiftLint, it would make  `sourcekitten` can't be builded in SourceKitten by SPM. :disappointed: 
I think current SPM does not support using dependency that contains main executable target and library target in same  repository.

For YamlSwift, I would write PR. But I also think it would be better doing it after release of next swift-DEVELOPMENT-SNAPSHOT that would contain changes of https://lists.swift.org/pipermail/swift-evolution-announce/2016-January/000027.html.

**Comment by jpsim** [comment]
Wow, that's all a big bag of hurt :disappointed:. Let's merge this, then I'll cut a release of SourceKitten once a release of Commandant is out (https://github.com/Carthage/Commandant/pull/50#issuecomment-178255316), so we can finally update this to point to them too.

Man, this SPM tool is a big pain at the moment. Early days, I guess.

**Comment by jpsim** [comment]
Wait, is there another reason you marked this as WIP, @norio-nomura? I think it can be merged now, since it will allow us to at least start testing this with SPM on CI.

**Comment by norio-nomura** [comment]
I did mark it as WIP for avoiding merge happens without these conversation while I'm in bed. (:3[ふとん]
Now, it has done. 😉

**Comment by jpsim** [comment]
Ha! Sorry if I woke you then :grimacing:. Let's get this in, and get you to sleep :zzz: !

Though you should really turn off your notifications!

**Comment by norio-nomura** [comment]
No problems!
Now, I'm walking in morning 🚶 and shooting pics of 🐞

**Comment by norio-nomura** [comment]
Thanks! :pray:

**Pull request merged**
