### PR TITLE
update README with cocoapod config file example

### PR DESCRIPTION
**Pull request by aerickson14**
Added further explanation in the `README` outlining how to setup a base `.swiftlint.yml` file by passing its location in using the `--config` option as part of the build script command.

### CODE REVIEW

**Comment by marcelofabri** [comment]
I'm not sure how this is only related to CocoaPods: you can pass `--config` to `swiftlint lint` no matter what distribution form you're using. 

Can you elaborate the motivation for this change?

**Comment by aerickson14** [comment]
Yep that's a fair point. I had found after installing the SwiftLint via CocoaPods and creating a base configuration in my projects root directory, I didnt realize that the config I had created wasnt being used. This is especially true for Cocoapods since the swiftlint executable gets installed in the `Pods/SwiftLint` directory. I would imagine the majority of SwiftLint installs via CocoaPods will want to be using the `--config` command in their build script.

**Comment by marcelofabri** [comment]
I don't think this is needed, since where the binary is located doesn't matter, what matters is where you run it from.

So running `Pods/SwiftLint/swiftlint` or `swiftlint` (from homebrew) on the project folder should give the same results.

**Comment by aerickson14** [comment]
That's the point though. Because when set up with CocoaPods swiftlint is getting run from `Pods/SwiftLint` which is not somewhere you would store your a project's `.swiftlint.yml` file.

Any time a project sets up SwiftLint as a pod, they will likely want to also provide the path to the `--config` file (which to me wasn't immediately obvious). I was expecting the `.swiftlint.yml` file in the SOURCE_ROOT to be picked up, but it wont unless `--config` is specified.

screenshot 2017-05-21 16 28 29

**Comment by marcelofabri** [comment]
aerickson14 what you described shouldn't happen. I've been using SwiftLint via CocoaPods successfully without passing `--config` in the build phase. If that's not working for you, I suggest you try to create a sample project showing the issue.

**Comment by jpsim** [comment]
I agree that this behavior shouldn't be happening.  If anyone provides steps to reproduce this behavior I'll be happy to consider a fix. Until then, we should close this.

**Pull request closed without merging**
