### PR TITLE
update recently added section on script input files in README

### PR DESCRIPTION
**Pull request by jpsim**
to more accurately reflect usage, ExtraBuildPhase plugin and further reading.

/cc @NachoSoto @norio-nomura

### CODE REVIEW

**Comment by NachoSoto** [comment]
Perfect 👍
I'll write a small bash command to define these variable based on `git ls-files -m` and I can create another PR documenting it as an example if you'd like.

**Comment by norio-nomura** [comment]
:+1:

**Comment by jpsim** [comment]
@NachoSoto cool! I'm wondering if baking that into SwiftLint might be even better?

**Comment by NachoSoto** [comment]
@jpsim maybe! I'll post here and we shall see :)

**Pull request merged**
