### PR TITLE
Fix all custom rules not being applied when any rule is configured incorrectly

### PR DESCRIPTION
**Pull request by marcelofabri**
Continued from #1681

// cc @JamieEdge

### CODE REVIEW

**Comment by marcelofabri** [comment]
Filled [SR-5477](https://bugs.swift.org/browse/SR-5477) 🙃 

Maybe we should just not run this test on Linux?

**Comment by jpsim** [comment]
This is great, especially the bit to annotate tests to not run on Linux. 😊 

However, why not misconfigure a rule in a cross-platform compatible way, so that we can benefit from this test on Linux without hitting SR-5477 (thanks for filing that, btw).

**Comment by marcelofabri** [comment]
🤔 

I didn't realize that there're other ways to fail inside `RegexConfiguration`. I'll open a new PR.

**Comment by JamieEdge** [comment]
Thanks for adding the tests - sorry I didn't get to it.

**Pull request merged**
