### PR TITLE
Use SwiftDeclarationAttributeKind instead of string constants

### PR DESCRIPTION
**Pull request by marcelofabri**
`SwiftDeclarationAttributeKind` was added in the latest release of SourceKitten 🎉

### CODE REVIEW

**Comment by jpsim** [comment]
Now that SourceKitten 0.20.0 is out, can we update this & merge?

**Comment by marcelofabri** [comment]
https://github.com/jpsim/SourceKitten/issues/512 needs to be released as well

**Comment by jpsim** [comment]
OK, will do.

**Comment by jpsim** [comment]
SourceKitten 0.21.0: https://github.com/jpsim/SourceKitten/releases/tag/0.21.0

**Pull request merged**
