### PR TITLE
Skip correcting files with parser diagnostics

### PR DESCRIPTION
**Pull request by jpsim**
We should avoid correcting files if they have parser errors or warnings, since SwiftLint isn't designed to handle all possibilities of invalid Swift code.

Generally, it's still useful for SwiftLint to _lint_ Swift files that don't parse 100% cleanly as a feedback mechanism, but we shouldn't attempt to _correct_ files with violations that don't parse cleanly, because that can mangle or delete code in unintended ways.

This PR also fixes many rule examples with parser diagnostics, but there are still over 500 rule examples with parser diagnostics, I don't have time to fix all of them, but we probably should do that eventually. I filed https://github.com/realm/SwiftLint/issues/3348 to track that, which is a good starter task if someone's interested in contributing to SwiftLint.

### CODE REVIEW

**Review by keith — APPROVED** [review]
awesome!

**Comment by marcelofabri** [comment]
I'm late to the party, but shouldn't we only skip files with errors? Warnings shouldn't affect SwiftLint's ability to format the code

**Comment by jpsim** [comment]
I agree, I'm supportive if you want to make that change @marcelofabri.

**Comment by marcelofabri** [comment]
> I agree, I'm supportive if you want to make that change @marcelofabri.

will do!

**Pull request merged**
