### PR TITLE
Stop triggering `strict_fileprivate` rule on protocol implementations

### LINKED ISSUE #4692: `strict_fileprivate` doesn't support private protocols
### New Issue Checklist

- [x] Updated SwiftLint to the latest version (0.50.3)
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The rule `strict_fileprivate` triggers an error when using `fileprivate` on methods from a private protocol.

It was said in  #1058, that
> "when using Swift 4, since basically it'll make possible to convert all the "acceptable" usages of fileprivate to private". 

However, this is not (no longer?) true since the swift compiler requires `fileprivate` when conforming to private protocol:
> Method 'aMethod()' must be declared fileprivate because it matches a requirement in private protocol 'APrivateProtocol'

### Environment

* SwiftLint version: 0.50.3
* Installation method used: Homebrew
* Paste your configuration file:

```yml
only_rules:
  - strict_fileprivate
```

* No [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)
* Xcode version: 14.1 - Build version: 14B47b
* Sample that shows the issue:
```swift
class AClass {
}

extension AClass: APrivateProtocol {

    fileprivate func aMethod() {
    }
}

private protocol APrivateProtocol {

    func aMethod()
}
```

### PR DESCRIPTION
**Pull request by SimplyDanny**
Fixes #4692.

### CODE REVIEW

**Comment by jpsim** [comment]
Could you please rebase this to re-run OSSCheck? It seems to have been having issues when this originally ran.

**Review by jpsim — APPROVED** [review]
Conceptually looks good to me, but let's re-run OSSCheck.

**Comment by SimplyDanny** [comment]
There was an exception for freestanding `fileprivate` functions that has now been fixed.

**Comment by SimplyDanny** [comment]
> Yet, it remains to check if all the fixed violations are valid.

All the remaining reported fixed violations are reasonable.

**Pull request merged**
