### PR TITLE
Have the Rule protocol define its members as non-static so that we ca…

### PR DESCRIPTION
**Pull request by aarondaub**
…n pass around instances of Rule

@jpsim

### CODE REVIEW

**Comment by aarondaub** [comment]
This addresses my issue #8. I believe it is necessary to make a fix for #3 (and later #4) possible.

**Comment by jpsim** [comment]
I agree that being able to pass around rule instances will make passing them around much simpler.

Could you add an entry to `CHANGELOG.md`? Otherwise this looks good.

**Comment by aarondaub** [comment]
@jpsim how do you want to handle merging? Should we squash the commits?

**Comment by jpsim** [comment]
Merged. For future notice, please add changelog entries as I did here: https://github.com/realm/SwiftLint/commit/a196c6acdb2768890405ca5202ac2e92d113986f

**Pull request merged**
