### PR TITLE
Add `test_tsan` target to Makefile

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by norio-nomura** [comment]
This is preparation for #2089.
Since the issue is caused by SourceKitten, it will need updating SourceKitten to fix #2089.
So, after confirming that `test_tsan` fails on CircleCI, disable that step in CircleCI.

**Comment by jpsim** [comment]
Nice work! Although let's not merge until it passes.

**Comment by norio-nomura** [comment]
Rebased and enabled on CircleCI.

**Comment by jpsim** [comment]
Nice! It must have been tricky to figure out exactly what the magic compiler flags needed to be!

**Pull request merged**
