### PR TITLE
Refactor `ASTRule` and add `SourceKitFreeRule`

### PR DESCRIPTION
**Pull request by norio-nomura**
- Make `ASTRule` to generic and remove `ASTBaseRule`
- Add `SourceKitFreeRule` and remove `RuleDescription.needsSourceKit`

### CODE REVIEW

**Comment by jpsim** [comment]
:+1: definitely an improvement

**Comment by norio-nomura** [comment]
`ASTBaseRule` and `RuleDescription.needsSourceKit` were introduced after latest release. So, I think those changes may not need to be added to CHANGELOG.

**Comment by jpsim** [comment]
I agree for the changelog. I'll just merge this then. Thanks for this @norio-nomura!

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
