### PR TITLE
Use `set -o pipefail` in .travis.yml

### PR DESCRIPTION
**Pull request by norio-nomura**
https://github.com/realm/SwiftLint/pull/397#issuecomment-174120359

### CODE REVIEW

**Comment by norio-nomura** [comment]
This PR fails test on [Travis](https://travis-ci.org/realm/SwiftLint/builds/104238215) as intended.

**Comment by jpsim** [comment]
So... why is this failing?

**Comment by norio-nomura** [comment]
It should have failed since https://github.com/realm/SwiftLint/pull/396 on [here](https://travis-ci.org/realm/SwiftLint/builds/104220106#L500).

**Comment by jpsim** [comment]
I'm sorry I'm being dense, I still don't understand. `Curry.framework` was removed, why is it 1) showing up in the Travis logs and 2) causing the build to fail? This branch has `Curry.framework` removed.

```
* dd102cb - (HEAD -> nn-use-pipefail, origin/nn-use-pipefail) Use `set -o pipefail` in .travis.yml (31 minutes ago) <Norio Nomura>
*   d425305 - (origin/master, origin/HEAD, master) Merge pull request #399 from realm/nn-reduce-creation-of-location (40 minutes ago) <JP Simard>
|\  
| * 7c4b7f3 - Reduce creation of `Location` (57 minutes ago) <Norio Nomura>
|/  
*   09d19e5 - Merge pull request #396 from realm/remove-curry (3 hours ago) <JP Simard>
|\  
| * 8012fab - (origin/remove-curry, remove-curry) remove Curry dependency (3 hours ago) <JP Simard>
|/  
*   e12b924 - Merge pull request #377 from marcelofabri/type-length-ignore-comments (12 hours ago) <JP Simard>
```

**Comment by norio-nomura** [comment]
SourceKitten 0.7.4 has following build phases:
screenshot 2016-01-23 13 03 36

It copies `Curry.framework` but not links to that. `Curry.framework` is not builded by SourceKittenFramework target. But, sourcekitten target links to `Curry.framework` and build it. So, it does not fail on SourceKitten.

On SwiftLint, SwiftLintFramework target builded `Curry.framework` instead of sourcekitten until e12b924.
After #396, no target builds `Curry.framework`, So SourceKittenFramework fails copying it.

**Comment by jpsim** [comment]
Oh wow, I was quite slow to understand that. Thanks for spelling it out for me. Let's merge #397 and then this.

**Comment by norio-nomura** [comment]
:+1:

**Pull request merged**
