### PR TITLE
Rewrite DiscouragedOptionalCollectionRule with SwiftSyntax

### PR DESCRIPTION
**Pull request by jpsim**

### CODE REVIEW

**Comment by jpsim** [comment]
I have to make some adjustments based on the OSSCheck results.

**Comment by jpsim** [comment]
I spot checked the differences reported by OSSCheck when ignoring columns and only looking at lines for rule violations and it all seems to be legit. Would like another maintainer to review and sign off before I merge though.

**Review by SimplyDanny — APPROVED** [review]
The new implementation looks impressively easy, especially compared to the previous one.

The OSS report looks good as well. I cannot think of another case that might be missing. The examples seem quite exhaustive, so the likelihood must be low for something to be not taken care of.

**Comment by jpsim** [comment]
Thanks for taking a look @SimplyDanny 🙏

**Pull request merged**
