### PR TITLE
Multiple Fixes for custom rules

### PR DESCRIPTION
**Pull request by fredpi**
Addresses #3472.

The reason why this issue occurred is that I didn't properly apply the new principle of _first defining all available rules and only then filtering those that are active depending on the mode_ to the custom rules. As you can see, I now moved the custom rules filtering logic to the same place where the normal rules get filtered so that the filtering isn't part of the custom rules merging algorithm.

### CODE REVIEW

**Comment by marcelofabri** [comment]
Can you add a test that would fail without this change so we avoid regressions in the future? 🙏

In the mean time, I'll test it against my project to confirm the fix

**Comment by fredpi** [comment]
@marcelofabri I thought about adding a test, but that would require me to leak some currently private interfaces of the `RulesWrapper` class across multiple layers. That may be worth it but I want to have a look at https://github.com/realm/SwiftLint/issues/3468 first to find out if an access level modification is needed anyway. I hope to find some time for that tomorrow.

**Comment by fredpi** [comment]
Linux tests failing because of a new Swift version... I guess this shouldn't get fixed within this PR.

**Comment by fredpi** [comment]
This PR also addresses #3468 now.

@marcelofabri I' rather not add the test you suggested as I can only think of a way of implementing it that would be depending largely on the implementation rather than on the result.

**Comment by fredpi** [comment]
Now also addresses #3477.

**Comment by fredpi** [comment]
As these are quite important fixes, I will test this again and probably merge it in some days' time, unless concerns emerge in the meantime.

**Pull request merged**
