### PR TITLE
Fix an issue: wrong line number and/or index is reported

### PR DESCRIPTION
**Pull request by crimsonwoods**
This PR will fix issue #213.

For a file containing multi-byte-characters (like Japanese-Hiragana, Kanji and more), `offset` parameter supplied to `NSString.lineAndCharacterForByteOffset` should be handled as a character-offset.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR!!! Shouldn't we rename `lineAndCharacterForByteOffset` to `lineAndCharacterForCharacterOffset` though?

**Comment by crimsonwoods** [comment]
We should do. I add a change to rename soon. And I might rebase this PR.

**Comment by crimsonwoods** [comment]
`lineAndCharacterForByteOffset` is renamed to `lineAndCharacterForCharacterOffset`.
And this PR is rebased.

@jpsim Would you review again?

**Comment by jpsim** [comment]
Looks good to me, how about you @keith?

**Comment by keith** [comment]
:shipit:

**Pull request merged**
