### PR TITLE
README: added note about --use-script-input-files

### LINKED ISSUE #334: [Feature request] Make autocorrect take an optional list of files
*Writing from my phone, so apologies if this is actually already possible and I didn't see it*.

I was thinking of adding a build phase that calls `swiftlint autocorrect` before actually linting, but I wouldn't want it to modify any file, only those that I've touched (to avoid too many changes but also to speed it up). This could by done by passing the list of "dirty" files on the `git`  checkout.

Other tools like `clang-tidy` can do this on a line-by-line basis too, which would be harder but definitely great!

### PR DESCRIPTION
**Pull request by NachoSoto**
This was introduced in #193, now it's documented! I also added `autocorrect` to the list of available commands in the `README`.

Closes #334.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Actually I should have tested this before writing the docs. It's not completely clear to me what the format of the environment variable is supposed to be. I see that it will read `SCRIPT_INPUT_FILE_COUNT` as well as `SCRIPT_INPUT_FILE_0`, `SCRIPT_INPUT_FILE_1`, ..., `SCRIPT_INPUT_FILE_${SCRIPT_INPUT_FILE_COUNT}`.

Wouldn't it have been easier to make it accept just one environment variable with a space-delimited string of paths? That would make it easier to use by being able to do something like:
```bash
export SCRIPT_INPUT_FILES=$(git ls-files -m)
```

**Comment by keith** [comment]
I'm not sure where this mechanism for sourcing files came from but it seems to be used in more places than just SwiftLint. Carthage implements this as well.

Also at least one possible problem with the space delimited approach would be having to deal with spaces in file paths.

**Comment by ikesyo** [comment]
The mechanism comes from Xcode's "Run Script" build phase and its "Input Files".

**Comment by jpsim** [comment]
:+1: thanks for this @NachoSoto!

**Comment by jpsim** [comment]
Oops, merged this a bit too quickly. Will adapt the docs to better reflect usage.

**Comment by norio-nomura** [comment]
I can't find any official documentation about `SCRIPT_INPUT_FILE_*` from apple, but found that the senior employee of Apple wrote about that in [2006](http://lists.apple.com/archives/Xcode-users/2006/Jan/msg00086.html), Xcode was version 2.2.

**Pull request merged**
