### PR TITLE
Fall back to line 1 when no line is provided & reporting with `xcode`

### PR DESCRIPTION
**Pull request by jpsim**
this is a generalization of the fix from #1521

### CODE REVIEW

**Comment by jpsim** [comment]
fyi @rhodgex1 / @rjhodge

**Comment by rjhodge** [comment]
Definitely like this solution way better than my one off fix.

**Comment by marcelofabri** [comment]
I don't know how I feel about different reporters having different locations 😬 

In the case of this particular rule, I'd keep the from #1521 as well

**Comment by jpsim** [comment]
> In the case of this particular rule, I'd keep the from #1521 as well

What do you mean by this?

**Comment by marcelofabri** [comment]
Sorry, shouldn't comment on PRs so late! 💤 

I meant that IMO [this](https://github.com/realm/SwiftLint/pull/1526/files#diff-c56abfa701d430bc5b3a2dd78dddc717L86) shouldn't be done. We should always trigger on the first line in that case in `file_header` rule.

**Pull request merged**
