### PR TITLE
chore(typo): fix typo on test

### PR DESCRIPTION
**Pull request by stavares843**

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks but please only include user-facing changes in the changelog in the future.

**Comment by stavares843** [comment]
thanks! 

I was not gonna add that but the bot mentioned to add the entry in the change log 🔨 

also, the CONTRIBUTING.md file also says
> When issuing a pull request, please add a summary of your changes to the CHANGELOG.md file.

it doens't specify to not add if is not user facing, both the bot and the CONTRIBUTING.md file 😄

**Comment by jpsim** [comment]
Thanks for flagging that, I've made the wording clearer in 73f4c3e99

**Comment by jpsim** [comment]
And in the Danger bot in dd4aefd23

**Pull request merged**
