### PR TITLE
Add Statement Position rule

### PR DESCRIPTION
**Pull request by S2dentik**
Else, else-if and catch statements being on the same line as the closing brace before them and one space after

### CODE REVIEW

**Comment by jpsim** [comment]
hmmm, it seems like there are lots of unrelated changes in here that either delete some useful comments or modifies whitespaces like adding/removing lines. This also needs rebasing to avoid merge conflicts.

Could you please update this PR to only apply the relevant changes?

Thanks!

**Comment by S2dentik** [comment]
Sorry for the whitespaces and newlines, they were for the other rules' integration test to pass. I have updated everything to the current check only.

**Comment by jpsim** [comment]
Could you please rebase this on master now that #177 has been merged? There are currently merge conflicts.

**Comment by jpsim** [comment]
Thanks!

**Pull request merged**
