### PR TITLE
Testing only TypeBodyLengthRule on testTypeBodyLengths

### PR DESCRIPTION
**Pull request by marcelofabri**
As commented on #377.

Also, IMO this probably doesn't reserve an entry in the changelog, so I haven't added it.

### CODE REVIEW

**Comment by jpsim** [comment]
Why not use the standard test approach here of having these go through `verifyRule()`, which already does this?

**Comment by marcelofabri** [comment]
Probably because `triggeringExamples` and `nonTriggeringExamples` would be large? Why didn't this rule called `verifyRule` before?

**Comment by jpsim** [comment]
> Probably because triggeringExamples and nonTriggeringExamples would be large? Why didn't this rule called verifyRule before?

I think the tests for this rule were originally written before the introduction of `verifyRule`. If `triggeringExamples` and `nonTriggeringExamples` are too large to have inline with the rule declaration, we could still construct a `RuleDescription` in this test and invoke `verifyRule` with it.

**Comment by jpsim** [comment]
Thanks for this, @marcelofabri but I've decided to do a more comprehensive clean up of rules tests in #408, so this won't be needed.

**Comment by marcelofabri** [comment]
:+1:

**Pull request closed without merging**
