### PR TITLE
Run Danger and OSSCheck on MacStadium instead of on Azure Pipelines

### PR DESCRIPTION
**Pull request by jpsim**
This will allow us to run OSSCheck on a bare metal Mac, which should make the OSSCheck performance results more reliable than running on virtual machines from Azure Pipelines.

### CODE REVIEW

**Comment by jpsim** [comment]
Promising so far! A no-op change had an average performance impact of less than 0.4% across all repos linted.

image

**Comment by norio-nomura** [comment]
How can we see the results of OSSCheck on MacStadium?

**Comment by jpsim** [comment]
It's a public pipeline, anyone can see it: https://buildkite.com/swiftlint/swiftlint/builds/5

**Comment by norio-nomura** [comment]
I didn't know that buildkite doesn't support GitHub Checks.
It can be reached from the link in the commit status to the log.
スクリーンショット 2019-11-06 9 19 30

**Comment by jpsim** [comment]
Ah yes, sorry that’s how I got to see the results.

**Comment by norio-nomura** [comment]
Is it possible to run [GitHub Actions self-hosted runner](https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/) on MacStadium instead of buildkite?

**Comment by jpsim** [comment]
Probably, but I saw that announcement immediately after finishing setting up buildkite 😆

**Pull request merged**
