### PR TITLE
Allow VariableNameRule to accept parameters

### PR DESCRIPTION
**Pull request by mmorier**
Hello
I make some changes in VariableNameRule to allow parameters to customize min and max lengths.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR @mmorier! I like the idea of making this rule parameterizable, but I think it'd be nicer to have 2 separate rules for this. We're seeing now how some rules are doing too much and that it's preferable to decouple them. It's also confusing to have the list of values passed in the YAML configuration being applied in different ways (mix/max). Every other rule, those values change the threshold between warning and error.

Now that we've merged #181, this has merge conflicts too.

Would you mind incorporating this feedback into your PR? Thanks for the contribution!

**Comment by mmorier** [comment]
Thanks @jpsim for your response. I imaginate that when I make this code in order to respect .warning and .error pattern.

I'll make this separation in 2 rules tomorrow and change my PR.

Thanks for SwiftLint, very helpful!

**Comment by mmorier** [comment]
Hello, I separated rules but I can create a new pull request. Did I close this one before ?

**Comment by jpsim** [comment]
There's no need to create a new pull request, you can rebase your changes onto the master branch and ping me once this is again ready for review.

**Comment by mmorier** [comment]
OK. I rebase my changes in one commit onto the master branch.
You can review it.

**Comment by jpsim** [comment]
This is great, nice work!

**Comment by mmorier** [comment]
Perfect!
Thanks for refactoring parameterRulesFromYAML in Configuration.

**Pull request merged**
