### PR TITLE
Fix Danger check for updated rules documentation

### PR DESCRIPTION
**Pull request by marcelofabri**

### CODE REVIEW

**Comment by jpsim** [comment]
What's going on with OSSCheck's report here? 3 Warnings and 117 Messages... 🤔

**Comment by jpsim** [comment]
Could you please rebase this so that OSSCheck runs properly?

**Comment by marcelofabri** [comment]
Any ideas why this is still showing warnings? 🤔

**Comment by jpsim** [comment]
Hmm, that's frustrating, I thought I had addressed the last OSSCheck issue 😞. I'll have to run locally to investigate.

**Comment by jpsim** [comment]
Can't reproduce the issue locally... I might create a bit of noise as I test this "in production"

**Comment by jpsim** [comment]
That shouldn't stop us from merging this PR though.

**Pull request merged**
