### PR TITLE
Fix non-root configs logging warnings more than once

### LINKED ISSUE #949: Lack of configuration file can lead to wall of output
I inherited a Xcode project that already had swiftlint integrated correctly. I wrote a number of custom rules in our `.swiftlint.yml` file and they immediately popped up in Xcode. All of those custom rules were configured to raise warnings so that they didn't block developers locally but would get caught on CI where we treated errors as warnings.

What I noticed was that swiftlint wasn't getting run on our CI boxes and I couldn't (and actually still  can't) figure out why. We are using Fastlane to run our tests on CI so when I googled `Fastlane swiftlint` I immediately got kicked to https://docs.fastlane.tools/actions/#swiftlint and attempted to add the `swiftlint` action to my Fastfile.

I added:
```
swiftlint(config_file: "my_company/.swiftlint.yml",
              strict: true,
              ignore_exit_status: false)
```

and I got the unexpected output of:

```
[11:45:21]: ▸ Linting 'AppDelegate.swift' (1/370)
[11:45:21]: ▸ configuration error: 'conditional_binding_cascade' is not a valid rule identifier
[11:45:21]: ▸ Valid rule identifiers:
[11:45:21]: ▸ opening_brace
[11:45:21]: ▸ empty_count
[11:45:21]: ▸ colon
[11:45:21]: ▸ type_name
[11:45:21]: ▸ explicit_init
[11:45:21]: ▸ trailing_semicolon
[11:45:21]: ▸ nimble_operator
[11:45:21]: ▸ force_unwrapping
[11:45:21]: ▸ mark
[11:45:21]: ▸ function_body_length
[11:45:21]: ▸ variable_name
[11:45:21]: ▸ vertical_whitespace
[11:45:21]: ▸ operator_whitespace
[11:45:21]: ▸ closure_spacing
[11:45:21]: ▸ legacy_constant
[11:45:21]: ▸ line_length
[11:45:21]: ▸ return_arrow_whitespace
[11:45:21]: ▸ private_unit_test
[11:45:21]: ▸ conditional_returns_on_newline
[11:45:21]: ▸ legacy_constructor
[11:45:21]: ▸ weak_delegate
[11:45:21]: ▸ valid_docs
[11:45:21]: ▸ file_length
[11:45:21]: ▸ valid_ibinspectable
[11:45:21]: ▸ legacy_nsgeometry_functions
[11:45:21]: ▸ trailing_newline
[11:45:21]: ▸ custom_rules
[11:45:21]: ▸ overridden_super_call
[11:45:21]: ▸ comma
[11:45:21]: ▸ force_cast
[11:45:21]: ▸ private_outlet
[11:45:21]: ▸ trailing_comma
[11:45:21]: ▸ force_try
[11:45:21]: ▸ nesting
[11:45:21]: ▸ function_parameter_count
[11:45:21]: ▸ control_statement
[11:45:21]: ▸ redundant_nil_coalescing
[11:45:21]: ▸ implicit_getter
[11:45:21]: ▸ trailing_whitespace
[11:45:21]: ▸ closing_brace
[11:45:21]: ▸ statement_position
[11:45:21]: ▸ type_body_length
[11:45:21]: ▸ todo
[11:45:21]: ▸ cyclomatic_complexity
[11:45:21]: ▸ missing_docs
[11:45:21]: ▸ switch_case_on_newline
[11:45:21]: ▸ syntactic_sugar
[11:45:21]: ▸ leading_whitespace
[11:45:21]: ▸ legacy_cggeometry_functions
[11:45:21]: ▸ Linting 'BankViewController.swift' (2/370)
[11:45:21]: ▸ configuration error: 'conditional_binding_cascade' is not a valid rule identifier
[11:45:21]: ▸ Valid rule identifiers:
[11:45:21]: ▸ opening_brace
[11:45:21]: ▸ empty_count
[11:45:21]: ▸ colon
[11:45:21]: ▸ type_name
[11:45:21]: ▸ explicit_init
[11:45:21]: ▸ trailing_semicolon
[11:45:21]: ▸ nimble_operator
[11:45:21]: ▸ force_unwrapping
[11:45:21]: ▸ mark
[11:45:21]: ▸ function_body_length
[11:45:21]: ▸ variable_name
[11:45:21]: ▸ vertical_whitespace
[11:45:21]: ▸ operator_whitespace
[11:45:21]: ▸ closure_spacing
[11:45:21]: ▸ legacy_constant
[11:45:21]: ▸ line_length
[11:45:21]: ▸ return_arrow_whitespace
[11:45:21]: ▸ private_unit_test
[11:45:21]: ▸ conditional_returns_on_newline
[11:45:21]: ▸ legacy_constructor
[11:45:21]: ▸ weak_delegate
[11:45:21]: ▸ valid_docs
[11:45:21]: ▸ file_length
[11:45:21]: ▸ valid_ibinspectable
[11:45:21]: ▸ legacy_nsgeometry_functions
[11:45:21]: ▸ trailing_newline
[11:45:21]: ▸ custom_rules
[11:45:21]: ▸ overridden_super_call
[11:45:21]: ▸ comma
[11:45:21]: ▸ force_cast
[11:45:21]: ▸ private_outlet
[11:45:21]: ▸ trailing_comma
[11:45:21]: ▸ force_try
[11:45:21]: ▸ nesting
[11:45:21]: ▸ function_parameter_count
[11:45:21]: ▸ control_statement
[11:45:21]: ▸ redundant_nil_coalescing
[11:45:21]: ▸ implicit_getter
[11:45:21]: ▸ trailing_whitespace
[11:45:21]: ▸ closing_brace
[11:45:21]: ▸ statement_position
[11:45:21]: ▸ type_body_length
[11:45:21]: ▸ todo
[11:45:21]: ▸ cyclomatic_complexity
[11:45:21]: ▸ missing_docs
[11:45:21]: ▸ switch_case_on_newline
[11:45:21]: ▸ syntactic_sugar
[11:45:21]: ▸ leading_whitespace
[11:45:21]: ▸ legacy_cggeometry_functions
```

For some reason the rules that were being used were being outputted for every file that was linted. With 370 files my console immediately became an unreadable mess.

The command that Fastlane was running was `swiftlint lint --strict --config my_company/.swiftlint.yml` and when I ran the command in the terminal I got the same output as above.

However when I `cd my_company` and ran `swiftlint lint --strict --config .swiftlint.yml` I got what you would expect. The rules only printed out once and then each file being linted was listed.

```
Loading configuration from '.swiftlint.yml'
configuration error: 'conditional_binding_cascade' is not a valid rule identifier
Valid rule identifiers:
opening_brace
empty_count
colon
type_name
explicit_init
trailing_semicolon
nimble_operator
force_unwrapping
mark
function_body_length
variable_name
vertical_whitespace
operator_whitespace
closure_spacing
legacy_constant
line_length
return_arrow_whitespace
private_unit_test
conditional_returns_on_newline
legacy_constructor
weak_delegate
valid_docs
file_length
valid_ibinspectable
legacy_nsgeometry_functions
trailing_newline
custom_rules
overridden_super_call
comma
force_cast
private_outlet
trailing_comma
force_try
nesting
function_parameter_count
control_statement
redundant_nil_coalescing
implicit_getter
trailing_whitespace
closing_brace
statement_position
type_body_length
todo
cyclomatic_complexity
missing_docs
switch_case_on_newline
syntactic_sugar
leading_whitespace
legacy_cggeometry_functions
Linting Swift files in current working directory
Linting 'AppDelegate.swift' (1/298)
Linting 'BankViewController.swift' (2/298)
Linting 'BankSearchViewController.swift' (3/298)
```

I then went back to the original directory, ran just `swiftlint` and got the same issue as before where every file that was linted outputted the rules being used.

It looks like if swiftlint doesn't have a configuration file specified or if one does not exist in the same directory that swiftlint is being run from there is some issue that causes the rules to be outputted for every file which gunks up the console.

### PR DESCRIPTION
**Pull request by jpsim**
Fixes #949.

### CODE REVIEW

**Comment by jpsim** [comment]
I've revived this. @reidmain I'd appreciate if you could confirm that this fixes #949 for you. Thanks for your patience!

**Comment by jpsim** [comment]
Merged in b19e0de6e4267f445c37df3ec882c264b5bebd02 & eef39595f6d5027df9aa7a3b1a241f2bd44e4a14.

**Comment by reidmain** [comment]
Alrighty I am on it. Looks like it has been merged into master so I will pull it down and build and test locally.

**Comment by reidmain** [comment]
OK this is weird. We were running SwiftLint 0.13.1 until last week when I updated to 0.18.1. I tried to replicate the problem before I built the master branch and I cannot do it. When I mimic the documented issue in https://github.com/realm/SwiftLint/issues/949 everything works as expected. The configuration file is being read correctly every time.

I ran the change through our CI environment and it also read the correct configuration file. The problem now is that SwiftLint seems to be run at a level higher than Xcode does so we are getting a ton more warnings because generated code violates some linter rules apparently. However this has nothing to do with the issue I reported so everything seems kosher.

**Pull request closed without merging**
