### PR TITLE
Added nested passes for colon_rule, for generics violations

### PR DESCRIPTION
**Pull request by a-25**

### CODE REVIEW

**Comment by rentateam-a-25** [comment]
Could anybody show what's wrong with checks? I want to fix if I can.

**Comment by marcelofabri** [comment]
> Could anybody show what's wrong with checks? I want to fix if I can.

You can't use `Self.` because we support compiling with Swift 5.0. You can use `type(of: self)` instead.

**Comment by rentateam-a-25** [comment]
@marcelofabri: thank you! Fixed it in last commit.
By the way, how may I discover that reason on my own? I tried to look in azure reports but didn't find detailed error description.

**Comment by marcelofabri** [comment]
@a-25 can you please rebase this? 🙌

**Comment by rentateam-a-25** [comment]
@marcelofabri: done

**Comment by a-25** [comment]
@marcelofabri: Are you going to merge this? It this PR valuable?

**Pull request closed without merging**
