### PR TITLE
Update SourceKitten

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix b2326b8 didn't update SourceKitten

### CODE REVIEW

**Comment by norio-nomura** [comment]
This will be updated after https://github.com/jpsim/SourceKitten/pull/198

**Comment by norio-nomura** [comment]
Updated.

**Comment by jpsim** [comment]
Thanks @norio-nomura! By the way, feel free to merge things yourself if you don't think they require review. On either this, or the SourceKitten repo. You've contributed nothing but awesome changes to these repos and I trust you fully!

**Comment by norio-nomura** [comment]
Thanks for merging!

> I trust you fully!

Thank you very much!

**Pull request merged**
