### PR TITLE
Add new `brace_on_new_line` option to `opening_brace` rule

### PR DESCRIPTION
**Pull request by SimplyDanny**

### CODE REVIEW

**Comment by SimplyDanny** [comment]
@buresdv: I think that would be it. Would you mind testing the new option by building SwiftLint yourself from [the branch](https://github.com/SimplyDanny/SwiftLint/tree/opening-brace-on-new-line)?

**Comment by buresdv** [comment]
Thank you so much for adding this! I have a very poor eyesight, which is why I put the braces on new lines. I'll test it and get back to you 😊

**Comment by buresdv** [comment]
I haven't used Swiftlint before, could you please give me a configuration I can use? I gave it a few tries, but it's not working properly, and I think the problem is me rather than the implementation😅

**Comment by SimplyDanny** [comment]
> I haven't used Swiftlint before, could you please give me a configuration I can use? I gave it a few tries, but it's not working properly, and I think the problem is me rather than the implementation😅

The simple configuration enabling only the `opening_brace` brace rule with the new option would be

```yml
included:
  - path/with/swift/files
only_rules:
  - opening_brace
opening_brace:
  brace_on_new_line: true
```

wherein you need to adapt the `included` section by providing some reasonable paths to lint.

With that, just running `swiftlint` in the folder containing the configuration should give you warnings (given that your source files contain code that violates the rule) and `swiftlint --fix` would even fix the violations automatically.

**Comment by buresdv** [comment]
Thank you! I think it worked :)

I used this code:
```
func sayHello(whatToSay: String? = nil) -> Void {
    if let whatToSay {
        print("Hello \(whatToSay)")
    } else {
        print("Hello world!")
    }
}
```

And got this output:
```
Linting Swift files in current working directory
Linting 'main.swift' (1/2)
Linting 'wrongBraces.swift' (2/2)
/Users/david/Developer/Playgrounds/SwiftlintTest/SwiftlintTest/wrongBraces.swift:12:54: warning: Opening Brace Spacing Violation: Opening brace should be on a separate line (opening_brace)
/Users/david/Developer/Playgrounds/SwiftlintTest/SwiftlintTest/wrongBraces.swift:13:22: warning: Opening Brace Spacing Violation: Opening brace should be on a separate line (opening_brace)
/Users/david/Developer/Playgrounds/SwiftlintTest/SwiftlintTest/wrongBraces.swift:15:12: warning: Opening Brace Spacing Violation: Opening brace should be on a separate line (opening_brace)
Done linting! Found 3 violations, 0 serious in 2 files.
```

I even tried it on one that might have been a false positive:
```
let string: [String] = ["a", "b", "c"]
let filteredString: [String] = string.filter({ !$0.contains("a") })
```
And it correctly didn't find any violations.

Thanks a lot! 😊

**Comment by SimplyDanny** [comment]
Thank you for checking it out. With this successful test, the PR is good to go and will be contained in the next release.

> I have a very poor eyesight, which is why I put the braces on new lines.

This is an important note showing that linters and formatters are not only about taste, style, consistency and prevention of bugs and performance issues but also are they helping to simplify the lives of some developers at least a little. Thank you for mentioning it! I took the liberty of noting this in the documentation. Hope that's fine.

**Comment by buresdv** [comment]
@SimplyDanny I wanted to thank you one more time for implementing this rule! ❤️ With this, I can finally start using SwiftLint for my projects. I'll add it to Cork once I'm done migrating it to Swift 6 (so you'll get a special shoutout in the credits!) 😉 

I immediately added it to my new project and it works perfectly. Thank you very much!!

Snímek obrazovky 2024-08-11 v 22 13 34

**Pull request merged**
