### PR TITLE
Add `empty_parameters` rule

### LINKED ISSUE #573: Add rule prefer `() -> ` over `Void -> `
Related to #570, we talked about another this.
In apple/swift, we can't find `Void ->`.
#570 can also be avoided by this.

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #573

I'm not a big fan of this rule name though 😅

### CODE REVIEW

**Comment by jpsim** [comment]
`VoidParametersRule`?

**Comment by marcelofabri** [comment]
I thought about that, but should rules describe what they catch or what it's the "right way"? 💭

**Comment by jpsim** [comment]
I actually like the "Empty Parameters" rule name.

**Comment by marcelofabri** [comment]
Let's keep then! I'll rebase the changelog

**Comment by jpsim** [comment]
I'll mark this as `[WIP]` until you can adapt to ignore "middle types" as discussed in https://github.com/realm/SwiftLint/pull/967#discussion_r91881943

**Comment by jpsim** [comment]
🎉

**Pull request merged**
