### PR TITLE
Exclude `weak_delegate` rule from autocorrection

### LINKED ISSUE #3577: Rule weak_delegate should not autocorrect
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The [weak_delegate](https://realm.github.io/SwiftLint/weak_delegate.html) rule is unique in that it actually changes the behavior of the code by autocorrecting `weak` to delegates.  It would be unsafe to apply this rule to a codebase as objects may now released that had previously been retained, leading to undefined behavior and bugs.

This rule is still useful as a warning to developers, but autocorrect should be disabled.

### PR DESCRIPTION
**Pull request by SimplyDanny**
Fixes #3577.

### CODE REVIEW

**Comment by SimplyDanny** [comment]
The build does not like me anymore. 😐 The TSan job is always failing with 
```
ERROR: Failed to query remote execution capabilities: UNAUTHENTICATED: no authentication metadata found
```
Anything I can do about it, @jpsim? It's the same for #4151 and #3989.

**Comment by jpsim** [comment]
I wonder if this is because I need to flip a flag in Azure Pipelines to allow external repos to access these credentials 🤔

Looking into it.

**Comment by jpsim** [comment]
Just checked this, let's see if that works.

image

**Comment by jpsim** [comment]
I give up. I may need to disable the remote cache on Azure Pipelines completely.

**Comment by jpsim** [comment]
ok I think it's working now.

**Comment by SimplyDanny** [comment]
> Not great, but the rule is flawed to start with.

Indeed. Thank you for looking into the build issues!

**Pull request merged**
