### PR TITLE
Invalidate cache when Swift patch version changes

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by jpsim** [comment]
The OSSCheck performance numbers are concerning. I'll run the job again to see if it was just a fluke. Original report here:

<details>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          12 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Aerial with this PR took 0.54s vs 0.41s on master (31% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Alamofire with this PR took 3.57s vs 3.38s on master (5% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Firefox with this PR took 16.95s vs 13.22s on master (28% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Kickstarter with this PR took 29.88s vs 20.56s on master (45% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Moya with this PR took 2.48s vs 1.78s on master (39% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Nimble with this PR took 2.66s vs 1.95s on master (36% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Quick with this PR took 0.93s vs 0.56s on master (66% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Realm with this PR took 4.68s vs 3.41s on master (37% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting SourceKitten with this PR took 1.34s vs 1.09s on master (22% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Sourcery with this PR took 5.05s vs 4.54s on master (11% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting Swift with this PR took 15.73s vs 14.95s on master (5% slower)</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linting WordPress with this PR took 13.32s vs 13.04s on master (2% slower)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>


</details>

**Comment by norio-nomura** [comment]
That may be caused by following:
```swift
extension SwiftVersion: Comparable {
    // Comparable
    static func < (lhs: SwiftVersion, rhs: SwiftVersion) -> Bool {
        return lhs.rawValue.compare(rhs.rawValue, options: .numeric) == .orderedAscending
    }
}
```
🤔  Numerical comparison may not be necessary.

**Comment by norio-nomura** [comment]
It looks Danger failed with error to editing https://github.com/realm/SwiftLint/pull/1949#issuecomment-344797979 in https://circleci.com/gh/realm/SwiftLint/2430

**Comment by norio-nomura** [comment]
It seems that Danger tries to edit comments containing specific strings and reuse them.
https://github.com/danger/danger/commit/6ebbc7e1f6d11f27037a7c21b33937b3d3d48944#diff-fa3d5768dcb09aa7d847372358083a77R54

**Comment by norio-nomura** [comment]
I have removed the string from https://github.com/realm/SwiftLint/pull/1949#issuecomment-344797979 and restarted osscheck.

**Comment by norio-nomura** [comment]
The OSSCheck performance tests result has been updated: https://github.com/realm/SwiftLint/pull/1949#issuecomment-344795405

**Comment by jpsim** [comment]
Thanks!

**Pull request merged**
