### PR TITLE
Added back 'missing_docs' (Nef10)

### PR DESCRIPTION
**Pull request by mattremmel**
Patch created from Nef10 (https://github.com/Nef10/SwiftLint.git) missing_docs branch, to remove merge commits that were preventing merging the PR (https://github.com/realm/SwiftLint/pull/2172).

These are not my changes, all credit goes to Nef10 (https://github.com/Nef10). This is replacing his PR (PR 2172: https://github.com/realm/SwiftLint/pull/2172), which couldn't be merged due to containing merge commits. I attempted to rebase his branch, but kept running into merge conflicts that I didn't know how to resolve. This is simply a patch created from the final git diff of his work.

### CODE REVIEW

**Comment by mattremmel** [comment]
Looks like it didn't patch correctly. Project is failing to build. I'll give it another try.

**Comment by mattremmel** [comment]
I looks like the LinuxMain.swift file, which appears generated by Sorcery, is the source of the problem. Not sure if it just needs re-run, or what.

**Comment by mattremmel** [comment]
I believe everything is fixed and working now.

**Comment by joshuatbrown** [comment]
This looks good to me. I'd love to have this functionality in SwiftLint.

**Comment by joshuatbrown** [comment]
@marcelofabri It looks like #2172 was good other than the merge commit(s), which is exactly what this PR addresses. Is there something we should do to get this reviewed?

**Comment by Nef10** [comment]
@mattremmel Thank you so much! I unfortunately didn't have any time at all to take care of this lately.

**Pull request merged**
