### PR TITLE
Update Commandant to 0.8.1

### LINKED ISSUE #309: Update Commandant to 0.8.1
Kinda tedious work, and it's not pressing because there's no functional change involved, but still filing this because it should be done eventually.

### PR DESCRIPTION
**Pull request by ikesyo**
Resolves #309.

### CODE REVIEW

**Comment by norio-nomura** [comment]
I tested and got following:
```
% swiftlint help rules
Display the list of rules and their identifiers

[1]    8066 illegal hardware instruction  swiftlint help rules

% swiftlint help version
Display the current version of SwiftLint

[1]    7121 illegal hardware instruction  swiftlint help version
```

**Comment by jpsim** [comment]
Works fine for me. Thanks @ikesyo! :bow: 

@norio-nomura are you sure it's not linking a different version of a framework in your build?

**Comment by jpsim** [comment]
Oops, I hadn't tried `help`, I'm also getting @norio-nomura's error. For example, running `swiftlint help rules`:

```
Display the list of rules and their identifiers

fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) bt
* thread #1: tid = 0x4f06e1, 0x00000001004bd258 libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> () + 40, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001004bd258 libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> () + 40
  * frame #1: 0x000000010017d754 Commandant`Commandant.CommandWrapper.(init <A><B where B: Commandant.CommandType, A == B.Options.ClientError, B.ClientError == B.Options.ClientError> (Commandant.CommandWrapper<A>.Type) -> (B) -> Commandant.CommandWrapper<A>).(closure #2) + 1524 at Command.swift:61
    frame #2: 0x000000010017bc3e Commandant`partial apply forwarder for Commandant.CommandWrapper.(init <A><B where B: Commandant.CommandType, A == B.Options.ClientError, B.ClientError == B.Options.ClientError> (Commandant.CommandWrapper<A>.Type) -> (B) -> Commandant.CommandWrapper<A>).(closure #2) + 126 at Command.swift:0
    frame #3: 0x0000000100164918 Commandant`Commandant.HelpCommand.run <A where A: Swift.ErrorType> (options=Commandant.HelpOptions<Commandant.CommandantError<()>> @ 0x00007fff5fbfdc70, self=Commandant.HelpCommand<Commandant.CommandantError<()>> @ 0x00007fff5fbfdc38)(Commandant.HelpOptions<A>) -> Result.Result<(), A> + 1256 at HelpCommand.swift:39
    frame #4: 0x000000010016677c Commandant`protocol witness for Commandant.CommandType.run <A where A: Commandant.CommandType> (A)(A.Options) -> Result.Result<(), A.ClientError> in conformance <A where A: Swift.ErrorType> Commandant.HelpCommand<A> : Commandant.CommandType in Commandant + 332 at HelpCommand.swift:35
    frame #5: 0x000000010017c59c Commandant`Commandant.CommandWrapper.(arguments=0x00006000000210e0, command=<unavailable>) -> (B) -> Commandant.CommandWrapper<A>).(closure #1) + 2252 at Command.swift:54
    frame #6: 0x000000010017bb66 Commandant`partial apply forwarder for Commandant.CommandWrapper.(init <A><B where B: Commandant.CommandType, A == B.Options.ClientError, B.ClientError == B.Options.ClientError> (Commandant.CommandWrapper<A>.Type) -> (B) -> Commandant.CommandWrapper<A>).(closure #1) + 198 at Command.swift:0
    frame #7: 0x00000001001793fa Commandant`Commandant.CommandRegistry.runCommand <A where A: Swift.ErrorType> (verb="help", arguments=1 value, self=0x0000600000020540)(Swift.String, arguments : Swift.Array<Swift.String>) -> Swift.Optional<Result.Result<(), Commandant.CommandantError<A>>> + 362 at Command.swift:100
    frame #8: 0x0000000100179f9b Commandant`Commandant.CommandRegistry.main <A where A: Swift.ErrorType> (arguments=3 values, defaultVerb="lint", errorHandler=(swiftlint`partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Commandant.CommandantError<()>) -> (@unowned ()) to @callee_owned (@in Commandant.CommandantError<()>) -> (@unowned ()) at main.swift), self=0x0000600000020540)(arguments : Swift.Array<Swift.String>, defaultVerb : Swift.String, errorHandler : (A) -> ()) -> () + 1643 at Command.swift:155
    frame #9: 0x0000000100179925 Commandant`Commandant.CommandRegistry.main <A where A: Swift.ErrorType> (defaultVerb="lint", errorHandler=(swiftlint`partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Commandant.CommandantError<()>) -> (@unowned ()) to @callee_owned (@in Commandant.CommandantError<()>) -> (@unowned ()) at main.swift), self=0x0000600000020540)(defaultVerb : Swift.String, errorHandler : (A) -> ()) -> () + 149 at Command.swift:125
    frame #10: 0x0000000100010ed8 swiftlint`main + 1128 at main.swift:21
    frame #11: 0x00007fff820f25ad libdyld.dylib`start + 1
    frame #12: 0x00007fff820f25ad libdyld.dylib`start + 1
(lldb) 
```

**Comment by jpsim** [comment]
Thanks for fixing that in Commandant, @ikesyo!

**Pull request merged**
