### PR TITLE
Adds opt-in prefixed_toplevel_constant rule

### PR DESCRIPTION
**Pull request by ornithocoder**
Implements #1907.

### CODE REVIEW

**Comment by marcelofabri** [comment]
@ornithocoder have you tried using (the lack of) `key.setter_accessibility` from the structure instead of using a regex? For example:

```json
{
  "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
  "key.substructure" : [
    {
      "key.nameoffset" : 4,
      "key.accessibility" : "source.lang.swift.accessibility.internal",
      "key.length" : 10,
      "key.name" : "x",
      "key.kind" : "source.lang.swift.decl.var.global",
      "key.namelength" : 1,
      "key.offset" : 0
    },
    {
      "key.nameoffset" : 15,
      "key.accessibility" : "source.lang.swift.accessibility.internal",
      "key.length" : 10,
      "key.name" : "y",
      "key.kind" : "source.lang.swift.decl.var.global",
      "key.offset" : 11,
      "key.namelength" : 1,
      "key.setter_accessibility" : "source.lang.swift.accessibility.internal"
    }
  ],
  "key.offset" : 0,
  "key.length" : 21
}
```

```swift
let x = ""
var y = ""
```

**Comment by ornithocoder** [comment]
@marcelofabri nope, but now I will! Thank you very much!

**Comment by ornithocoder** [comment]
Hmmm. The number of violations went up by ~200.

**Comment by ornithocoder** [comment]
Really interesting, it caught [this](https://github.com/apple/swift/blob/6a34e3e9cd59e81426bc8a8a73684d35da586369/stdlib/private/SwiftPrivateLibcExtras/SwiftPrivateLibcExtras.swift#L40:12) (which makes sense).

**Comment by marcelofabri** [comment]
You could check if `key.bodylength` if is `nil` or not. Although it's probably debatable if global computed properties should trigger or not as they can act as constants.

**Comment by ornithocoder** [comment]
@marcelofabri the numbers are back to normal now :-)

**Pull request merged**
