### PR TITLE
Upload Docker Image in to Github Container

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description
This PR just uses GitHub Actions for generating a docker image and uploading it to the GitHub Docker Containers.

It generates a docker image when:
- A commit is done in the `master` branch, generating `latest` version.
- A tag is done, generating `{git tag}` version.

Additionally, I have added some missing libraries and I have increased Ubuntu to the Focal version.

Thanks

### CODE REVIEW

**Review by jpsim — APPROVED** [review]
Thanks for your contribution! Could you please make a new PR documenting how to use this docker image?

**Comment by jpsim** [comment]
> Could you please make a new PR documenting how to use this docker image?

This is neat. GitHub Actions already pushed a container and I could lint all files in the current directory with this command:

```
$ docker run -it -v `pwd`:`pwd` -w `pwd` ghcr.io/realm/swiftlint:latest
Linting Swift files in current working directory
Linting 'RuleDocumentation.swift' (1/490)
...
Linting 'YamlSwiftLintTests.swift' (490/490)
Done linting! Found 0 violations, 0 serious in 490 files.
```

**Comment by fjtrujy** [comment]
> > Could you please make a new PR documenting how to use this docker image?
> 
> This is neat. GitHub Actions already pushed a container and I could lint all files in the current directory with this command:
> 
> ```
> $ docker run -it -v `pwd`:`pwd` -w `pwd` ghcr.io/realm/swiftlint:latest
> Linting Swift files in current working directory
> Linting 'RuleDocumentation.swift' (1/490)
> ...
> Linting 'YamlSwiftLintTests.swift' (490/490)
> Done linting! Found 0 violations, 0 serious in 490 files.
> ```

Exactly, it pushes a docker image to the GitHub registry container and you can use it. I don't mind writing documentation but so far it is going to be exactly the same that you wrote above.

**Comment by jpsim** [comment]
> Exactly, it pushes a docker image to the GitHub registry container and you can use it. I don't mind writing documentation but so far it is going to be exactly the same that you wrote above.

Yeah doesn't need to be any more than what I wrote, but it'd be helpful to have these steps be made visible in the README.

**Comment by fjtrujy** [comment]
> > Exactly, it pushes a docker image to the GitHub registry container and you can use it. I don't mind writing documentation but so far it is going to be exactly the same that you wrote above.
> 
> Yeah doesn't need to be any more than what I wrote, but it'd be helpful to have these steps be made visible in the README.

Here you have it
https://github.com/realm/SwiftLint/pull/3808

Thanks

**Comment by fjtrujy** [comment]
By the way, I don't know if it was clear enough in the description of the PR.
But if you create a new `tag` in the repo, it also will create a new docker image following the convention
```
ghcr.io/realm/swiftlint:${tag_name}
```

Thanks

**Pull request merged**
