### PR TITLE
Add JUnit reporter

### PR DESCRIPTION
**Pull request by matthewellis**
I needed to pull test results from SwiftLint into Bamboo CI but the current reporters where not compatible with the parsers available, JUnit seems to be a common format for a few tools so i thought i would put in a pull request to add this to the project.

### CODE REVIEW

**Comment by jpsim** [comment]
Could you please add tests to `ReporterTests.swit`?

**Comment by jpsim** [comment]
This will also need a changelog entry according to `CONTRIBUTING.md`, and to update the `README.md`. Otherwise looks good. Thanks!

**Comment by matthewellis** [comment]
Hey @jpsim thanks for the feedback,  i have made the changes you asked for.

**Comment by jpsim** [comment]
Looks great, thanks!

**Pull request merged**
