### PR TITLE
Add new `if_let_shadowing` rule

### LINKED ISSUE #4202: if let from Swift 5.7
Suggestion to add a rule to help finding code that can be changed to use the short version of if let,

```
if let foo = foo {
  bar(foo)
}
```
to:
```
if let foo {
  bar(foo)
}
```

I've used this in my .yml which does the trick for my code, but I'm sure it can be improved to cover more cases:

```
  use_short_if_let:
    name: "Use short if let"
    regex: "if let (\\w*) = \\1(,| {)"
    capture_group: 0
    severity: warning
```

### PR DESCRIPTION
**Pull request by SimplyDanny**
Closes #4202.

### CODE REVIEW

**Comment by marcelofabri** [comment]
Should this be opt-in?

**Comment by SimplyDanny** [comment]
> Should this be opt-in?

You think so? In a Swift 5.7 code base, this would be a welcome rule and I feel like the false-positive rate should be low. This is no strong opinion, though. I'm also fine with making it optional.

**Comment by marcelofabri** [comment]
> > Should this be opt-in?
> 
> You think so? In a Swift 5.7 code base, this would be a welcome rule and I feel like the false-positive rate should be low. This is no strong opinion, though. I'm also fine with making it optional.

IIRC, the evolution thread for that feature was somewhat controversial - this was even in the list of "things the Swift team won't consider proposals for".

I guess up to this day I'm still a little uncomfortable with making rules enabled by default as many developers consider SwiftLint the ultimate source of truth™ for styles vs using it as a tool and configuring it properly.

**Comment by SimplyDanny** [comment]
Okay ... you convinced me. Let's make it optional.

Do you have ideas for more test cases? The ones I added are all quite simple. I cannot think of anything more elaborated, though.

**Comment by marcelofabri** [comment]
Maybe it’s worth it temporarily removing the min Swift version so OSS check can run it

**Comment by CraigSiemens** [comment]
> Do you have ideas for more test cases? The ones I added are all quite simple. I cannot think of anything more elaborated, though.

Here's some of the ones I've run into in our project that I think could be added.

Non triggering
```swift
if let i = i as? Foo
```

Triggering
```swift
if someCondition, ↓let j = j {
if someCondition,
   ↓let j = j {

// I'm not sure how multiple matches on a line work 🙃
if ↓let i = i, ↓let j = j {

if ↓let i = i,
   ↓let j = j {

// and the guard variants of those
```

**Comment by marcelofabri** [comment]
Another one to watch out for: `where` conditions

**Comment by SimplyDanny** [comment]
> Another one to watch out for: `where` conditions

Would you give me an example? I don't think optional bindings are allowed in where-clauses.

**Comment by SimplyDanny** [comment]
> Maybe it’s worth it temporarily removing the min Swift version so OSS check can run it

Done. The samples I have checked look reasonable. Almost all are fairly standard.

**Comment by CraigSiemens** [comment]
> > Another one to watch out for: `where` conditions
> 
> Would you give me an example, @marcelofabri? I don't think optional bindings are allowed in where-clauses.

I think he's referring to `where` and `repeat-where` loops that have conditions. I though where-clauses at first too 😄.

**Comment by marcelofabri** [comment]
> > > Another one to watch out for: `where` conditions
> > 
> > 
> > Would you give me an example, @marcelofabri? I don't think optional bindings are allowed in where-clauses.
> 
> I think he's referring to `where` and `repeat-where` loops that have conditions. I thought where-clauses at first too 😄.

I was thinking about where clauses - I guess I didn’t sleep enough 😆

**Comment by SimplyDanny** [comment]
> > > Another one to watch out for: `where` conditions
> > 
> > 
> > Would you give me an example, @marcelofabri? I don't think optional bindings are allowed in where-clauses.
> 
> I think he's referring to `where` and `repeat-where` loops that have conditions. I thought where-clauses at first too 😄.

I now think you are both referring to `while` and `repeat-while` loops actually. 🤔 If so, I've just added test cases for `while` loops at least. If you still mean something else, please let me know. 😅

Fun fact: The [Swift reference for `repeat-while` loops](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#grammar_repeat-while-statement) states that the condition in the `while` can be an optional binding while the grammar rule expects expressions only. The grammar rule seem to be correct since this is also what SwiftSyntax and the Swift compiler accept. I'll create a fix for the documentation.

That being said, I'm confident now that all possible optional bindings are covered.

**Comment by CraigSiemens** [comment]
> I now think you are both referring to `while` and `repeat-while` loops actually.

Yeah, I was thinking about `while` loops. Apparently I mix up words that look like `wh__e` 😆.

Otherwise, looks good to me.

**Comment by eneko** [comment]
Will this rule be auto-correctable?

**Comment by SimplyDanny** [comment]
> Will this rule be auto-correctable?

Yes, it will be.

**Review by CraigSiemens — APPROVED** [review]

**Pull request merged**
