### PR TITLE
Make `emoji` and `checkstyle` reporter to output report sorted by file name

### LINKED ISSUE #1429: `TestCheckstyleReporter` and `testEmojiReporter` sometimes fail on Swift 3.1 for Linux
Since the enumeration of the dictionary is indefinite order.
e.g. https://travis-ci.org/realm/SwiftLint/jobs/221323293#L561-L571

### PR DESCRIPTION
**Pull request by norio-nomura**
Fixes #1429

### CODE REVIEW

**Comment by norio-nomura** [comment]
String comparison result is different between mac and Linux ... 😞 
```terminal.sh-session
$ TOOLCHAINS=org.swift.31120170327a swift
swift_oss_helper command enabled.
warning: (x86_64) /Library/Developer/Toolchains/swift-3.1-RELEASE.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Resources/repl_swift empty dSYM file detected, dSYM was created with an executable with no debug info.
Welcome to Apple Swift version 3.1 (swift-3.1-RELEASE). Type :help for assistance.
  1> "Other" < "filename"
$R0: Bool = true
  2>  
```
```terminal.sh-session
$ docker run --privileged -it -v `pwd`:`pwd`:cached -w `pwd` --rm norionomura/sourcekit:31 swift
Welcome to Swift version 3.1 (swift-3.1-RELEASE). Type :help for assistance.
  1> "Other" < "filename"
$R0: Bool = false
  2>  
```

**Comment by norio-nomura** [comment]
[SR-530](https://bugs.swift.org/browse/SR-530)

**Comment by norio-nomura** [comment]
[StringComparable.swift#L111-L112](https://github.com/apple/swift/blob/fc6add388026b54a6b1142bcc3d77231dc9be017/stdlib/public/core/StringComparable.swift#L111-L112):
```swift
  public  // @testable
  func _compareString(_ rhs: String) -> Int {
#if _runtime(_ObjC)
    // We only want to perform this optimization on objc runtimes. Elsewhere,
    // we will make it follow the unicode collation algorithm even for ASCII.
    if _core.isASCII && rhs._core.isASCII {
      return _compareASCII(rhs)
    }
#endif
    return _compareDeterministicUnicodeCollation(rhs)
  }
```
When comparing ASCII character strings, there seems to be a difference depending on whether ObjC runtime is present:
- If present, the same behavior as Foundation
- If not, the behavior defined by Unicode

I think that the value expected for our test results should be switched depending on whether ObjC runtime is present or not.

**Comment by norio-nomura** [comment]
Updated.

**Comment by jpsim** [comment]
Also, way to fix this in Swift! 👏 

(https://github.com/apple/swift/pull/8769)

**Comment by norio-nomura** [comment]
Thanks! 🙏 

> Also, way to fix this in Swift! 👏

Apparently, https://github.com/apple/swift/pull/8769 seems to be incompatible with the String Manifesto.

**Pull request merged**
