### PR TITLE
Fatal error message rule

### PR DESCRIPTION
**Pull request by kimdv**
Started on a rule request #1348 

I don't know id this is the most efficient way to do, but I started and now we can continue the work from here 😸

### CODE REVIEW

**Comment by marcelofabri** [comment]
@kimdv Thanks for contributing! I've made a few changes and made the rule enabled by default. 
I want to check oss-check, but we're having a few issues with it right now (#1369).

**Comment by marcelofabri** [comment]
I've run it locally and it found 506 violations. I still think ideologically this should be a default rule, but maybe it shouldn't since there're so many violations. Thoughts, @jpsim?

**Comment by kimdv** [comment]
@marcelofabri I partly agree. I think it's a good idea to have it enabled by default, because it is good behaviour to write why there is a fatalError. It makes it easier, specially in opensource projects to get a good overview of the code.

**Comment by marcelofabri** [comment]
I thought more about this and I think it should be opt-in until we implement #1379.

**Pull request merged**
