### PR TITLE
Fix false positive on vertical_parameter_alignment

### LINKED ISSUE #1129: False positive on vertical_parameter_alignment with default parameters in multiple lines
This shouldn't trigger:

```swift
internal func regex(_ pattern: String,
                    options: NSRegularExpression.Options = [.anchorsMatchLines,
                                                            .dotMatchesLineSeparators]) -> NSRegularExpression 
```

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #1129

### CODE REVIEW

**Comment by marcelofabri** [comment]
@jpsim Can we enable Circle for forks as well? 🤔

**Comment by jpsim** [comment]
> Can we enable Circle for forks as well? 🤔

I didn't know that needed to be explicitly enabled. Could you please open a new dummy PR (maybe with a tiny change to the app's source) to make sure Circle and OSSCheck run as expected? I think I may have seen a log from Danger saying that it didn't run due to a commit push before a PR not actually being tied to a PR.

**Comment by marcelofabri** [comment]
I've just force pushed this again to make sure it runs 🚀

**Comment by jpsim** [comment]
> I've just force pushed this again to make sure it runs 🚀

Could you please open a new dummy PR too? I want to make sure a commit pushed prior to a PR existing still runs Danger correctly.

**Comment by marcelofabri** [comment]
> Could you please open a new dummy PR too? 

Done: https://github.com/realm/SwiftLint/pull/1137

**Pull request merged**
