### PR TITLE
add `--quiet` flag to `lint` and `autocorrect` commands

### PR DESCRIPTION
**Pull request by jpsim**
addresses #386.

depends on #495. /cc @scottrhoyt @norio-nomura 

**update:** no longer depends on #495 since that's since been merged.

### CODE REVIEW

**Comment by jpsim** [comment]
> This is not mentioned in the man page

SwiftLint doesn't generate a man page. Do you mean the `--help` output? I see the `--quiet` flag in there:

```console
$ swiftlint lint --help
OVERVIEW: Print lint warnings and errors

USAGE: swiftlint lint [<options>] [<paths> ...]

ARGUMENTS:
  <paths>  List of paths to the files or directories to lint.

OPTIONS:
...
  --quiet  Don't print status logs like 'Linting <file>' & 'Done linting'.
...
```

**Comment by DaniSpringer** [comment]
repos % swiftlint --help
OVERVIEW: A tool to enforce Swift style and conventions.

USAGE: swiftlint <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  analyze                 Run analysis rules
  docs                    Open SwiftLint documentation website in the default
                          web browser
  generate-docs           Generates markdown documentation for all rules
  lint (default)          Print lint warnings and errors
  rules                   Display the list of rules and their identifiers
  version                 Display the current version of SwiftLint

  See 'swiftlint help <subcommand>' for detailed help.
repos %

**Comment by jpsim** [comment]
Please run `swiftlint lint --help` to get all the help usage info for the `lint` subcommand.

**Comment by DaniSpringer** [comment]
> Please run `swiftlint lint --help` to get all the help usage info for the `lint` subcommand.

Thank you!

**Pull request merged**
