### PR TITLE
Add `flatmap_over_map_reduce` opt-in rule

### LINKED ISSUE #2883: [Rule Request] Prefer flatMap instead of map { }.reduce([], +)
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

`flatMap` can be used instead of `map { ... }.reduce([], +)` to avoid iterating the collection twice.

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

```swift
let foo = bar.map { $0.array }.reduce([], +) // would trigger

let foo = bar.map { $0.int }.reduce(0, +) // ok
let foo = bar.flatMap { $0.array } // ok
``` 

3. Should the rule be configurable, if so what parameters should be configurable?

Just the severity.

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.

Opt-in as this can have false positives

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #2883

### CODE REVIEW

**Comment by jpsim** [comment]
Why opt-in?

**Comment by jpsim** [comment]
Also, isn't curious that _nothing_ in OSSCheck triggered this?

**Comment by marcelofabri** [comment]
> Why opt-in?

The other similar rules are opt-in. In theory there could be a type that implements `map` but not `flatMap`

**Comment by jpsim** [comment]
Can this support the `reduce(into:)` variant?

**Comment by marcelofabri** [comment]
> Can this support the `reduce(into:)` variant?

it could, but it's more complicated because we need to analyze the closure (although we probably should also do it for the tradicional `reduce`). I just wanted something quick that would catch the more obvious (and what I thought to be more common) case as this showed up in a PR that I was reviewing today.

**Comment by marcelofabri** [comment]
> Also, isn't curious that _nothing_ in OSSCheck triggered this?

I was able to get a warning on SwiftLint itself by changing

```swift
let allPaths = paths.flatMap { $0 }
```

to 

```swift
 let allPaths = paths.map { $0 }.reduce([], +)
```

So I guess this is just not a common issue? Or at least in this form, using `+` as the parameter.

**Pull request merged**
