### PR TITLE
fix false positives for enums and private functions with `redundant_objc_attribute` rule

### LINKED ISSUE #4633: `redundant_objc_attribute` false positives after updating 0.49.1->0.50.1
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`redundant_objc_attribute` false positives after updating 0.49.1->0.50.1

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.50.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? pre-commit
* Paste your configuration file:

```yml
# insert yaml contents here
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. No
* Which Xcode version are you using (check `xcodebuild -version`)? 14.0.1
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
@objc public extension Foo {
  // This shouldn't trigger the warning
  @objc enum Bar: Int {
    case bar
  }
  // This will have compiler error without the @objc
  var bar: Bar { .bar }
  // This also triggers a warning and also causes compiler error but a better fix would be to mark other private interfaces @nonobjc
  @objc private enum Baz: Int {
    case baz
  }
  private var baz: Baz { .baz }
}
```

### PR DESCRIPTION
**Pull request by Cyberbeni**
fixes #4633

other examples of this rule might also need updating

### CODE REVIEW

**Comment by Cyberbeni** [comment]
ah, private is also bad for stored property

**Comment by Cyberbeni** [comment]
Should probably also also check for other types, not just enums: https://github.com/realm/SwiftLint/blob/449190d32406f7ae6aa9fdb7ecb2360c517e9483/Source/SwiftLintFramework/Rules/Idiomatic/RedundantObjcAttributeRule.swift#L66

**Comment by jpsim** [comment]
Thanks for the PR!

> Should probably also also check for other types, not just enums:

Do you want to fix this in this PR or as a follow-up?

**Comment by Cyberbeni** [comment]
I'll check what the compiler says about them tomorrow and fix them.

**Comment by Cyberbeni** [comment]
seems like class doesn't need `@objc`, it just needs to be subclassed from NSObject (tested with declaring an `@objc` variable), same with typealias, haven't tried struct/actor, enum requires `@objc` (and also having an Int rawValue)

functions (for `#selector`) need `@objc` if private

variables (for NSObject's value(forKey:)) only need to be marked `@objc` if inside class declaration and private, stored or calculated doesn't matter

tests would probably still need some more fixing up but I won't have time for that anytime soon. for example some of them don't even have valid syntax, like `Example("private @GKInspectable var foo: String! {}"),`

**Comment by mildm8nnered** [comment]
I've been playing around with this issue and then found this branch.

I think there are some problems here:

Consider the non-triggering example

```
@objcMembers
class Foo {
    class Bar: NSObject {
        @objc var foo: Any
    }
}
```

Actually, consider a slight variant, which will actually compile:

```
@objcMembers
class Foo: NSObject {
    class Bar: NSObject {
        @objc var foo: Any?
    }
}
```

This does not trigger, which is ok, but in the `-Swift.h` header, this will produce:

```
SWIFT_CLASS("_TtC12Sportscode643Foo")
@interface Foo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
```

Now consider

```
@objcMembers
class Foo: NSObject {
    @objc
    class Bar: NSObject {
        @objc var foo: Any?
    }
}
```

this will trigger, but the `@objc` is required here to expose Bar to ObjC - this code produces

```
SWIFT_CLASS("_TtC12Sportscode643Foo")
@interface Foo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC12Sportscode643Foo3Bar")
@interface Bar : NSObject
@property (nonatomic) id _Nullable foo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
```

These were not errors before this branch. 

Similarly, the triggering example

```
        @objcMembers
        class Foo {
            ↓@objc var bar: Any?
            ↓@objc var foo: Any?
            ↓@objc
            class Bar {
                @objc
                var foo: Any?
            }
        }
```

I believe this should not trigger for the `@objc` before the class.

**Pull request closed without merging**
