### PR TITLE
Make empty_parentheses_with_trailing_closure correctable

### PR DESCRIPTION
**Pull request by marcelofabri**

### CODE REVIEW

**Comment by jpsim** [comment]
> This PR may need tests.

Hmm... I wonder if we can "teach" Danger that some of our tests are actually defined in `RuleDescription` 🤔

**Comment by marcelofabri** [comment]
> Hmm... I wonder if we can "teach" Danger that some of our tests are actually defined in RuleDescription 🤔
Well, we still need to add them in Tests when adding the rule 🤔

**Comment by jpsim** [comment]
Yes, but only for new rules.

**Comment by marcelofabri** [comment]
We can check if the modified files are just existing rules and skip the warning in this case.

**Pull request merged**
