### PR TITLE
Report lint duration changes in Danger

### PR DESCRIPTION
**Pull request by jpsim**
Addresses #376.

Also adds Alamofire to osscheck and improves Danger log output. /cc @marcelofabri @scottrhoyt

### CODE REVIEW

**Comment by jpsim** [comment]
Hmmm, unfortunately Travis doesn't provide very repeatable lint times...

As of f4a8986, no changes were made to SwiftLint, yet runs were ~50% slower than `master`:

image

We're already linting 5 times and taking the average, so linting more wouldn't lead to more reproducible results...

I'm not sure how we can make this more reliable.

**Comment by marcelofabri** [comment]
Maybe we could try Circle CI to see if it's more reliable? 😬

**Comment by jpsim** [comment]
Heh, what do you know. Much more reliable on Circle CI!

image

However, one of my assumptions was incorrect... disabling parallelization doesn't have a major impact on performance in this case, probably because Circle (and likely Travis too) must just run their VMs with a single virtual processor.

I'll try something else to attempt to simulate a performance regression.

**Comment by marcelofabri** [comment]
Maybe you could disable cache in `File+Cache` instead? Enabling opt-in rules made the number of violations grow so much that Danger couldn't post to GitHub:

```
  message: body is too long (maximum is 65536 characters) // See: https://developer.github.com/v3/issues/comments/#edit-a-comment
```

**Comment by marcelofabri** [comment]
👏

**Pull request merged**
