### PR TITLE
Excluding Pods files by default (fix #6)

### LINKED ISSUE #6: Don't check cocoapods
Maybe make it optional by specifying it in the config file (#3), but it's probably a sensible default as well. Unless this already shouldn't be happening and I messed it up :grin:

### PR DESCRIPTION
**Pull request by GlaucoNeves**
A start point to make SwiftLint configurable to chose which folders to scan.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR, but I'd really rather have the ability to exclude folders explicitly rather than have some hardcoded exceptions for `Pods/` and `Carthage/`.

**Comment by GlaucoNeves** [comment]
Agreed. Do you already have an idea of how this should be configured? Maybe passed as parameters when invoked the SwiftLint? I can take a look in that.

**Comment by jpsim** [comment]
Yes, a Commandant parameter would be appropriate for this I think.

**Comment by eneko** [comment]
Any updates on this? I think this belongs to the `.swiftlint.yml` configuration file, is there any PR for that yet?

**Comment by jpsim** [comment]
> Any updates on this? I think this belongs to the .swiftlint.yml configuration file, is there any PR for that yet?

not yet!

**Comment by jakecraige** [comment]
Since the config has been merged, should this be closed?

**Comment by jpsim** [comment]
> Since the config #99 has been merged, should this be closed?

Yes, I'd say so. `Pods/` and `Carthage/` directories still aren't excluded by default, but it's now trivial to do by adding those directories to a `.swiftlint.yml`

**Pull request closed without merging**
