### PR TITLE
Added a rule to enforce where colons can go in Dictionary type declar…

### PR DESCRIPTION
**Pull request by codeman9**
…ations and literals.

### CODE REVIEW

**Comment by jpsim** [comment]
Instead of creating a new rule for this, I think we should just expand the current ColonRule to support dictionaries. What do you think?

**Comment by codeman9** [comment]
I was thinking about that, too. Would you think another configuration option would be appropriate? Something like "apply_to_dictionaries: true"?

**Comment by jpsim** [comment]
That works.

**Comment by codeman9** [comment]
Not intentional. I will update. Thanks!

**Pull request closed without merging**
