### PR TITLE
Add `--progress` flag to lint and analyze commands

### PR DESCRIPTION
**Pull request by jpsim**
Inspired by https://github.com/jkandzi/Progress.swift

```
4948 of 29100 [=====                         ] ETA: 44s (540 files/s)
```

Demo:

[asciicast](https://asciinema.org/a/517985)

### CODE REVIEW

**Comment by jpsim** [comment]
There are still problems with this clobbering the output, causing some violations to not be visible in the command line output.

**Comment by jpsim** [comment]
> There are still problems with this clobbering the output, causing some violations to not be visible in the command line output.

I fixed this by deferring printing the violations until all files have been processed.

**Review by SimplyDanny — APPROVED** [review]
This is cool!

**Comment by jpsim** [comment]
> I fixed this by deferring printing the violations until all files have been processed.

I still need to do this for corrections before I can merge this.

**Comment by jpsim** [comment]
> > I fixed this by deferring printing the violations until all files have been processed.
> 
> I still need to do this for corrections before I can merge this.

Done in b5b47a773bffadb86276db2dc7c1cd6257b5fc45

**Pull request merged**
