### PR TITLE
Optimize `excludingPattern` in `violatingOpeningBraceRanges()`

### LINKED ISSUE #491: Performance issue on linting KeychainAccess with 0.8.0
On linting https://github.com/kishikawakatsumi/KeychainAccess,
0.7.2:
```
swiftlint lint --config ~/.swiftlint-test.yml  3.44s user 0.15s system 91% cpu 3.931 total
```
0.8.0:
```
swiftlint lint --config ~/.swiftlint-test.yml  29.61s user 0.18s system 98% cpu 30.175 total
```

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix #491
By applying this, on linting KeychainAccess,
from(0.8.0):
```
swiftlint lint --config ~/.swiftlint-test.yml  29.61s user 0.18s system 98% cpu 30.175 total
```
to:
```
swiftlint lint --config ~/.swiftlint-test.yml  1.92s user 0.06s system 91% cpu 2.160 total
```

### CODE REVIEW

**Comment by jpsim** [comment]
This looks good to me, but @scottrhoyt should confirm.

**Comment by scottrhoyt** [comment]
That's much better. Thanks for fixing this, @norio-nomura !

**Comment by jpsim** [comment]
Cool, let's pull this in then.

**Comment by norio-nomura** [comment]
:smile:

**Pull request merged**
