### PR TITLE
Update Commandant to 0.8.2

### PR DESCRIPTION
**Pull request by ikesyo**
https://github.com/realm/SwiftLint/pull/312#issuecomment-168558053 is fixed. :zap:

### CODE REVIEW

**Comment by jpsim** [comment]
:+1: thanks for fixing :smile: 

Related to Commandant, could you please take a look at the Homebrew/homebrew#47688 failure? I think it might have something to Commandant build settings, but I've hit a dead end debugging it.

**Comment by ikesyo** [comment]
Commandant itself is not using `install_name_tool`, so that seems to be related to the changes in #244. How about adding `-Wl,-headerpad_max_install_names` to `OTHER_LDFLAGS` of `swiftlint` target? (maybe related: https://github.com/Homebrew/homebrew/issues/20233)

**Comment by norio-nomura** [comment]
I simulated Homebrew's bottling process on local mac and got same error to the [build log](https://travis-ci.org/Homebrew/homebrew/jobs/100220482)
Build log with `--debug` option are following:
```log
% GIT=/usr/bin/git brew install --verbose --build-bottle swiftlint --debug
…
** INSTALL SUCCEEDED **

mkdir -p "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Library/Frameworks" "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/usr/local/bin"
mv -f "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Applications/swiftlint.app/Contents/Frameworks/SwiftLintFramework.framework" "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Library/Frameworks/SwiftLintFramework.framework"
mv -f "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Applications/swiftlint.app/Contents/MacOS/swiftlint" "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/usr/local/bin/swiftlint"
rm -rf "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Applications/swiftlint.app"
install_name_tool -delete_rpath "@executable_path/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/usr/local/bin/swiftlint"
mkdir -p "/usr/local/Cellar/swiftlint/0.5.5/Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin"
cp -Rf "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/Library/Frameworks/SwiftLintFramework.framework" "/usr/local/Cellar/swiftlint/0.5.5/Frameworks/"
cp -f "/private/tmp/swiftlint20160109-15328-16p8ppt/SwiftLint.dst/usr/local/bin/swiftlint" "/usr/local/Cellar/swiftlint/0.5.5/bin/"
install_name_tool -rpath "/Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "@executable_path/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin/swiftlint"
install_name_tool -rpath "/Library/Frameworks" "@executable_path/../Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin/swiftlint"
==> Cleaning
Fixing /usr/local/Cellar/swiftlint/0.5.5/bin/swiftlint permissions from 755 to 555
==> Finishing up
ln -s ../Cellar/swiftlint/0.5.5/bin/swiftlint swiftlint
ln -s ../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Resources Resources
ln -s ../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/SwiftLintFramework SwiftLintFramework
ln -s ../../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A A
ln -s ../../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/Current Current
Changing dylib ID of /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
  from @rpath/Commandant.framework/Commandant
    to /usr/local/opt/swiftlint/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
Error: Failed to fix install names
The formula built, but you may encounter issues using it or linking other
formula against it.
==> Failure while executing: /usr/bin/install_name_tool -id /usr/local/opt/swiftlint/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
/usr/local/Library/Homebrew/keg_relocate.rb:118:in `install_name_tool'
/usr/local/Library/Homebrew/keg_relocate.rb:77:in `change_dylib_id'
/usr/local/Library/Homebrew/keg_relocate.rb:8:in `block (2 levels) in fix_install_names'
/usr/local/Library/Homebrew/extend/pathname.rb:360:in `ensure_writable'
/usr/local/Library/Homebrew/keg_relocate.rb:7:in `block in fix_install_names'
/usr/local/Library/Homebrew/keg_relocate.rb:6:in `each'
/usr/local/Library/Homebrew/keg_relocate.rb:6:in `fix_install_names'
/usr/local/Library/Homebrew/formula_installer.rb:675:in `fix_install_names'
/usr/local/Library/Homebrew/formula_installer.rb:453:in `finish'
/usr/local/Library/Homebrew/cmd/install.rb:216:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:143:in `<main>'
==> Summary
```

It seems building SwiftLint is completed.
But Homebrew's bottling process contains running `install_name_tool`, and that fails
```
Changing dylib ID of /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
  from @rpath/Commandant.framework/Commandant
    to /usr/local/opt/swiftlint/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
Error: Failed to fix install names
The formula built, but you may encounter issues using it or linking other
formula against it.
==> Failure while executing: /usr/bin/install_name_tool -id /usr/local/opt/swiftlint/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
```

I think #244 does not cause this.

> How about adding -Wl,-headerpad_max_install_names to OTHER_LDFLAGS of swiftlint target? (maybe related: Homebrew/homebrew#20233)

Maybe we need to passing the flag to Commandant's build process.

**Comment by norio-nomura** [comment]
I succeed the build by using following Formula:
```ruby
class Swiftlint < Formula
  desc "Experimental tool to enforce Swift style and conventions"
  homepage "https://github.com/realm/SwiftLint"
  url "https://github.com/realm/SwiftLint.git", :tag => "0.5.5", :revision => "3b9aa3bb4d63784574900b7140c0ad89cc4c468d"
  head "https://github.com/realm/SwiftLint.git"

  bottle do
    cellar :any
    sha256 "7c20de6100924cfc93b5275abb3db522aaca401095d0eb73a15478c49d1e0454" => :el_capitan
    sha256 "f9fa5f5e1ef845bf3967539d7d9fbd930fb734c7e16c50edf23d3c7e75e5a37b" => :yosemite
  end

  depends_on :xcode => ["7.1", :build]

  def install
    system "sh", "-c", "echo OTHER_LDFLAGS=-Wl,-headerpad_max_install_names>flag.xcconfig"
    system "sed", "-i", "\"\"", "s/XCODEFLAGS=/XCODEFLAGS=-xcconfig flag.xcconfig /", "Makefile"
    system "make", "prefix_install", "PREFIX=#{prefix}", "TEMPORARY_FOLDER=#{buildpath}/SwiftLint.dst"
  end

  test do
    (testpath/"Test.swift").write "import Foundation\n"
    system "#{bin}/swiftlint"
  end
end
```

Log:
```
% GIT=/usr/bin/git brew install --verbose --build-bottle swiftlint
…
==> make prefix_install PREFIX=/usr/local/Cellar/swiftlint/0.5.5 TEMPORARY_FOLDER=/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst
rm -f "SwiftLint.pkg"
script/bootstrap
rm -rf "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst"
xcodebuild -xcconfig flag.xcconfig -workspace 'SwiftLint.xcworkspace' -scheme 'swiftlint' DSTROOT=/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst clean
*** Updating submodules...
Build settings from command line:
    DSTROOT = /private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst

Build settings from configuration file 'flag.xcconfig':
    OTHER_LDFLAGS = -Wl,-headerpad_max_install_names

=== CLEAN TARGET Curry-Mac OF PROJECT Curry WITH CONFIGURATION Debug ===
…
** INSTALL SUCCEEDED **

mkdir -p "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Library/Frameworks" "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/usr/local/bin"
mv -f "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Applications/swiftlint.app/Contents/Frameworks/SwiftLintFramework.framework" "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Library/Frameworks/SwiftLintFramework.framework"
mv -f "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Applications/swiftlint.app/Contents/MacOS/swiftlint" "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/usr/local/bin/swiftlint"
rm -rf "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Applications/swiftlint.app"
install_name_tool -delete_rpath "@executable_path/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/usr/local/bin/swiftlint"
mkdir -p "/usr/local/Cellar/swiftlint/0.5.5/Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin"
cp -Rf "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/Library/Frameworks/SwiftLintFramework.framework" "/usr/local/Cellar/swiftlint/0.5.5/Frameworks/"
cp -f "/private/tmp/swiftlint20160109-57898-11o19ur/SwiftLint.dst/usr/local/bin/swiftlint" "/usr/local/Cellar/swiftlint/0.5.5/bin/"
install_name_tool -rpath "/Library/Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "@executable_path/../Frameworks/SwiftLintFramework.framework/Versions/Current/Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin/swiftlint"
install_name_tool -rpath "/Library/Frameworks" "@executable_path/../Frameworks" "/usr/local/Cellar/swiftlint/0.5.5/bin/swiftlint"
==> Cleaning
==> Finishing up
ln -s ../Cellar/swiftlint/0.5.5/bin/swiftlint swiftlint
ln -s ../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Resources Resources
ln -s ../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/SwiftLintFramework SwiftLintFramework
ln -s ../../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A A
ln -s ../../../Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/Current Current
==> Summary
🍺  /usr/local/Cellar/swiftlint/0.5.5: 43 files, 15M, built in 1 minute 34 seconds
```

**Comment by ikesyo** [comment]
> Maybe we need to passing the flag to Commandant's build process.

IIUC the flag shoud be set for the target which is modified by `install_name_tool`, not for the library targets who are linked with the parent product.

**Comment by norio-nomura** [comment]
The build log with `--debug` said following:
> ==> Failure while executing: /usr/bin/install_name_tool -id /usr/local/opt/swiftlint/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant /usr/local/Cellar/swiftlint/0.5.5/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant

Homebrew tried to modify Commandant.

**Comment by norio-nomura** [comment]
`XCODEBUILD(1)` said:
> -xcconfig filename
>           Load the build settings defined in filename when building all targets.  These settings will override all other settings, including settings passed individually on the command line.

and I confirmed that the flag has been passed to build phase of Commandant on using modified Formula as following:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/BuildProductsPath/Release -F/Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/BuildProductsPath/Release -filelist /Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/IntermediateBuildFilesPath/Commandant.build/Release/Commandant.build/Objects-normal/x86_64/Commandant.LinkFileList -install_name @rpath/Commandant.framework/Commandant -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/../Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mmacosx-version-min=10.9 **-Wl,-headerpad_max_install_names** -fapplication-extension -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -force_load -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a -Xlinker -add_ast_path -Xlinker /Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/IntermediateBuildFilesPath/Commandant.build/Release/Commandant.build/Objects-normal/x86_64/Commandant.swiftmodule -framework Result -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/IntermediateBuildFilesPath/Commandant.build/Release/Commandant.build/Objects-normal/x86_64/Commandant_dependency_info.dat -o /Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-gubgqnmdsuarjgasduyqvjtdadpe/Build/Intermediates/ArchiveIntermediates/swiftlint/IntermediateBuildFilesPath/UninstalledProducts/macosx/Commandant.framework/Versions/A/Commandant

**Comment by jpsim** [comment]
@norio-nomura how do you suggest we solve this?

**Comment by norio-nomura** [comment]
@jpsim I just pushed https://github.com/realm/SwiftLint/pull/346.

**Pull request merged**
