### PR TITLE
Adds support for excluded in custom rules

### PR DESCRIPTION
**Pull request by nigelflack**
Adds support for excluded in custom rules to specify a regex for files to exclude.

### CODE REVIEW

**Comment by marcelofabri** [comment]
Maybe we need to rethink the name since this can be confused with https://github.com/realm/SwiftLint/issues/1408. 

I've seen that you actually opened a ticket to discuss the potentially confusing names: https://github.com/realm/SwiftLint/issues/1353

**Comment by nigelflack** [comment]
Yes I'll look at adding some tests. Sorry... first github contribution :-)

And I've updated #1353 with some further thoughts.

**Comment by marcelofabri** [comment]
This looks good to me, but could you add some documentation about this on README?

**Comment by marcelofabri** [comment]
Thanks! 💯

**Pull request merged**
