### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by jpsim**
@norio-nomura do you know if we need to do anything else to properly reflect the `YamlSwift` -> `Yams` dependency change in SourceKittenFramework?

I don't think so, but I'm not 100% sure. Like maybe Yams needs to be added to `components.plist`?

### CODE REVIEW

**Comment by norio-nomura** [comment]
It might needs to add `Yams.framework` to "Embed Frameworks into SwiftLintFramework.framework" build phase in `swiftlint` target. But, swiftlint does not use function that needs Yams and works without that.

**Comment by norio-nomura** [comment]
> But, swiftlint does not use function that needs Yams and works without that.

That was incorrect.
We need to add `Yams.framework` to "Embed Frameworks into SwiftLintFramework.framework" build phase in swiftlint target.

**Comment by norio-nomura** [comment]
Running `make install` in SwiftLint working tree causes installing `/Library/Frameworks/Yams.framework`.
It seems the project configuration of Yams is wrong.

**Comment by norio-nomura** [comment]
Sorry, I didn't notice that SourceKitten also installs `/Library/Frameworks/Yams.framework`:
```terminal.session
$ pkgutil --payload-files ~/Downloads/SourceKitten.pkg 
.
./Applications
./Library
./Library/Frameworks
./Library/Frameworks/Yams.framework
./Library/Frameworks/Yams.framework/Headers
./Library/Frameworks/Yams.framework/Modules
./Library/Frameworks/Yams.framework/Resources
./Library/Frameworks/Yams.framework/Versions
./Library/Frameworks/Yams.framework/Versions/A
./Library/Frameworks/Yams.framework/Versions/A/Headers
./Library/Frameworks/Yams.framework/Versions/A/Headers/yaml.h
./Library/Frameworks/Yams.framework/Versions/A/Headers/Yams-Swift.h
./Library/Frameworks/Yams.framework/Versions/A/Modules
./Library/Frameworks/Yams.framework/Versions/A/Modules/module.modulemap
./Library/Frameworks/Yams.framework/Versions/A/Modules/Yams.swiftmodule
./Library/Frameworks/Yams.framework/Versions/A/Modules/Yams.swiftmodule/x86_64.swiftdoc
./Library/Frameworks/Yams.framework/Versions/A/Modules/Yams.swiftmodule/x86_64.swiftmodule
./Library/Frameworks/Yams.framework/Versions/A/Resources
./Library/Frameworks/Yams.framework/Versions/A/Resources/Info.plist
./Library/Frameworks/Yams.framework/Versions/A/Yams
./Library/Frameworks/Yams.framework/Versions/Current
./Library/Frameworks/Yams.framework/Yams
./usr
./usr/local
./usr/local/bin
./usr/local/bin/sourcekitten
./usr/local/Frameworks
./usr/local/Frameworks/SourceKittenFramework.framework
./usr/local/Frameworks/SourceKittenFramework.framework/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/SourceKittenFramework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Commandant
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Commandant
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/A/Resources/Info.plist
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Commandant.framework/Versions/Current
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftCore.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftCoreGraphics.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftDarwin.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftDispatch.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftFoundation.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftIOKit.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/libswiftObjectiveC.dylib
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Result
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/A
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/A/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/A/Resources/Info.plist
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/A/Result
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Result.framework/Versions/Current
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/SWXMLHash
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/Resources/Info.plist
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/A/SWXMLHash
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/SWXMLHash.framework/Versions/Current
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/A
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/A/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/A/Resources/Info.plist
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/A/Yams
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Versions/Current
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Frameworks/Yams.framework/Yams
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Resources
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/Resources/Info.plist
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/A/SourceKittenFramework
./usr/local/Frameworks/SourceKittenFramework.framework/Versions/Current
```

**Comment by jpsim** [comment]
Thanks for fixing Yams, @norio-nomura! I've released Yams 0.1.4, integrated it into SourceKitten, released SourceKitten 0.16.0, added `Yams.framework` to the "Embed Frameworks into
SwiftLintFramework.framework" build phase and updated all dependencies to their latest versions.

**Comment by jpsim** [comment]
Hmmm, `make package` is failing for me...

```
error: The following binaries use incompatible versions of Swift:
/tmp/SwiftLint.dst/Applications/swiftlint.app/Contents/Frameworks/SwiftLintFramework.framework/Versions/A/Frameworks/Commandant.framework/Commandant
/tmp/SwiftLint.dst/Applications/swiftlint.app/Contents/MacOS/swiftlint
```

Full output here: https://gist.github.com/jpsim/43b7a5f70043d8e1888da07766fcc6f4

Any ideas as to why that would be happening?

**Comment by norio-nomura** [comment]
It worked for me: https://gist.github.com/norio-nomura/c2e70fef36d4bfc83062863e07a2da61

**Comment by jpsim** [comment]
Strange. Maybe it's getting confused because I have so many versions of Xcode installed (7.3.1, 8.0, 8.1, 8.2).

Anyway, I don't think that should stop us from merging this since I also get that error when running on `master`. Thanks for the help @norio-nomura!

**Comment by jpsim** [comment]
I don't know which one it was, but I cleaned out a bunch of stuff locally and then it worked!

```
$ git clean -xdf
$ rm -rf Packages ~/Library/Developer/Xcode/DerivedData /tmp/*.dst /usr/local/Frameworks
```

**Pull request merged**
