### PR TITLE
Fix directories with a '.swift' suffix being treated as files

### LINKED ISSUE #1948: 0.24.0 issues with folder names
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

Partial output, sorry. Full output is huge
```bash
Linting 'GRMustache.swift' (96/858)
error opening input file 'path/.../GRMustache.swift' (Is a directory)
Most rules will be skipped because sourcekitd has failed.
Linting 'ViewController.swift' (97/858)
Linting 'AppDelegate.swift' (98/858)
Linting 'OSXTests.swift' (99/858)
Linting 'iOSTests.swift' (100/858)
Linting 'ViewController.swift' (101/858)
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=257 "The file “GRMustache.swift” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=path/.../GRMustache.swift, NSUnderlyingError=0x7f90e4299ff0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.69.2/src/swift/stdlib/public/core/ErrorType.swift, line 181
Illegal instruction: 4
```

### Environment

0.24.0
homebrew

Pulled from config
```yml
excluded:
  - GRMustache.swift
  - MKCommon/Theming/Fonts/FontAwesome.swift
```

Latest xcode 9 build
No example, sorry

### My report
It appears that swift lint is ignoring some folders now in the excluded config because of the directory name containing a "."
For example: 
GRMustache.swift/
FontAwesome.swift/

It looks like swiftlint is having trouble opening this directory because its treating it as a file anyway, though it appears that my exclusion in our config file is being ignored. Anyone else experiencing this as of updating?

### PR DESCRIPTION
**Pull request by JamieEdge**
Fixes #1948.

### CODE REVIEW

**Comment by marcelofabri** [comment]
@JamieEdge The CI failure looks legit, could you please take a look? Thanks!

**Comment by JamieEdge** [comment]
@marcelofabri, certainly, it should be fixed now. I tested the alternative approach and it should handle extra slashes ok too (e.g. "/some/path/" + "/" + "File.swift" works).

**Comment by jpsim** [comment]
Thanks for the PR @JamieEdge, and sorry for the delay in getting back to you, I don't have much SwiftLint time lately.

I'd feel much more comfortable merging this if you added a regression test, something that would've failed without your change.

Maybe you could add a Swift file in a `*.swift` directory in the fixtures in [ProjectMock](https://github.com/realm/SwiftLint/tree/master/Tests/SwiftLintFrameworkTests/Resources/ProjectMock) and add a related test in [ConfigurationTests.swift](https://github.com/realm/SwiftLint/blob/0.24.0/Tests/SwiftLintFrameworkTests/ConfigurationTests.swift)?

Thanks!

**Comment by JamieEdge** [comment]
No problem at all! I’ll get this updated at the weekend to include a test.

**Comment by JamieEdge** [comment]
I've added the test however really not sure why it's failing in that single instance on CircleCI. The files in the mock project folder seem to be completely different?

**Comment by jpsim** [comment]
There are two jobs failing on CI. The first is that there's a merge commit in this branch. Please only use commits on top of `master` by rebasing. The second is `ConfigurationTests.testLintablePaths` with SwiftPM on macOS only, though I haven't looked into why just yet.

**Comment by JamieEdge** [comment]
Thanks - I’ll squash all of the commits down to avoid the merge and will continue looking at why that specific test is failing.

**Comment by jpsim** [comment]
At the very least, it looks like you'll need to run `make sourcery` since the test wasn't added to the linux manifest, which is why it's not running on Linux.

```diff
--- a/Tests/LinuxMain.swift
+++ b/Tests/LinuxMain.swift
@@ -66,6 +66,7 @@ extension ConfigurationTests {
         ("testDisabledRulesWithUnknownRule", testDisabledRulesWithUnknownRule),
         ("testDuplicatedRules", testDuplicatedRules),
         ("testExcludedPaths", testExcludedPaths),
+        ("testLintablePaths", testLintablePaths),
         ("testIsEqualTo", testIsEqualTo),
         ("testIsNotEqualTo", testIsNotEqualTo),
         ("testCustomConfiguration", testCustomConfiguration),
@@ -376,6 +377,7 @@ extension RulesTests {
         ("testEmptyEnumArguments", testEmptyEnumArguments),
         ("testEmptyParameters", testEmptyParameters),
         ("testEmptyParenthesesWithTrailingClosure", testEmptyParenthesesWithTrailingClosure),
+        ("testExplicitACL", testExplicitACL),
         ("testExplicitEnumRawValue", testExplicitEnumRawValue),
         ("testExplicitInit", testExplicitInit),
         ("testExplicitTopLevelACL", testExplicitTopLevelACL),
@@ -455,7 +457,8 @@ extension RulesTests {
         ("testVoidReturn", testVoidReturn),
         ("testSuperCall", testSuperCall),
         ("testWeakDelegate", testWeakDelegate),
-        ("testXCTFailMessage", testXCTFailMessage)
+        ("testXCTFailMessage", testXCTFailMessage),
+        ("testYodaConditionRule", testYodaConditionRule)
     ]
 }
```

Actually, it seems like `master` is missing a few other tests added outside this PR. I'll fix that right away.

**Comment by jpsim** [comment]
`master` updated in e574f1fcc65b46b3999d83ced4ee42f0970383cd

**Comment by jpsim** [comment]
@JamieEdge are you still working on this?

**Comment by marcelofabri** [comment]
Merged in #2047. Thanks, @JamieEdge! 👏

**Pull request closed without merging**
