### PR TITLE
Use prebuildCommand for SwiftLint plugin

### PR DESCRIPTION
**Pull request by evfemist**
using `.prebuildCommand` instead `.buildCommand` fixes error `Entry point (_main) undefined. for architecture arm64` that was mention in [#4641](https://github.com/realm/SwiftLint/issues/4641) and [#4628](https://github.com/realm/SwiftLint/issues/4628)

Also in this PR I fix issue that cache files was added to bundle.

### CODE REVIEW

**Comment by ckuburlis** [comment]
Works well for me. Without this I was getting some weird errors `Executable path is a Directory` and my app was trying to add swiftLint as a resource. This solved both of the issues for me.

**Comment by ryanjfar** [comment]
Is it possible to have this Merged? it fixed the error I was getting from the Xcode build plugin as well, `Executable path is a Directory`

**Comment by ApolloZhu** [comment]
This change also fixes missing "ProduceName-Swift.h" error in mixed Swift and Objective-C project

**Comment by evfemist** [comment]
Merged with latest `main`, all checks have passed 😉

**Review by SimplyDanny — APPROVED** [review]

**Comment by SimplyDanny** [comment]
Merged. Thank you @evfemist!

**Comment by tonyarnold** [comment]
Sadly, this change makes SwiftLint unusable in my project - exclude paths are entirely ignored, and I'm seeing hundreds of thousands of errors and warnings from things that should be excluded. 

FYI: The issue with `Entry point (_main) undefined. for architecture arm64` is an Xcode bug that can be worked around using #4732 until the SwiftPM team have implemented additional API to handle how input files are consumed.

**Comment by tonyarnold** [comment]
It looks like appending `--force-exclude` as an argument fixes exclude paths being ignored. I'll put together a PR for it now. 

I'm still not sure that `prebuildCommand` is the correct tool for this job, and the documentation for it makes mention of the performance impacts:

> Because prebuild commands are run on every build, they are can have significant performance impact and should only be used when there is no way to know the names of the outputs before the command is run.

Also, while my understanding was correct about the differences between the two approaches, given that we're not writing any "real" outputs, both of the approaches are going to run on every build. So there's no performance gain to be had from `buildCommand` at this time.

**Comment by evfemist** [comment]
Hi @tonyarnold, looks like there are difference when `swiftlint` runs in Xcode and when in terminal.
I have tried to run same command as produced by plugin in terminal - and all works fine without `--force-exclude`

**Pull request merged**
