### PR TITLE
Updated README with a list of rules coming from `swiftlint rules`

### PR DESCRIPTION
**Pull request by jschmid**

### CODE REVIEW

**Comment by keith** [comment]
I'm not sure we want to keep these 2 data sources in sync. This seems particularly error prone to me. Maybe we remove this and just have advice for how users can see the real list locally?

**Comment by jschmid** [comment]
I agree with you. This was just a quick fix. 

See my updated commit.

**Comment by keith** [comment]
Looks good to me! Mind squashing these commits? After that we should be good to merge!

**Comment by jschmid** [comment]
There you go !

**Comment by keith** [comment]
Thanks!

**Comment by jpsim** [comment]
The sample YAML in the README was never meant to be a canonical source of all rules, but it kind of just became that over time. This is much better, thanks!

**Pull request merged**
