### PR TITLE
Revert "Fix finding the nested config when a single file path is passed"

### PR DESCRIPTION
**Pull request by jpsim**
Reverts realm/SwiftLint#3342

This caused a regression in one of my projects. cc @sethfri 

It's a closed source project so it'll take some time for me to craft a repro case.

### CODE REVIEW

**Comment by sethfri** [comment]
Interesting! Thanks for the tag. Lmk once you're able to get a repro case together; I'd be more than happy to take another stab at a fix!

**Comment by jpsim** [comment]
Yeah, sorry for the lack of details yet. I have to reduce what we're doing to something I can share here.

**Comment by jpsim** [comment]
It has something to do with specifying an out-of-tree config file while linting a directory that already has a `.swiftlint.yml` file at its root.

**Comment by sethfri** [comment]
@jpsim That's helpful, thanks! Is the behavior you're seeing that the passed in file is ignored in favor of the root .swiftlint.yml?

**Comment by jpsim** [comment]
I think so.

**Comment by sethfri** [comment]
What is the expected behavior in that scenario @jpsim? Should the root file be completely ignored in favor of the passed in file, or would we expect them to be merged?

**Comment by jpsim** [comment]
Hmmm, good question. I can see arguments for either way. In almost every other case we merge configurations with parents.

**Comment by sethfri** [comment]
@jpsim Personally I would expect the config argument to be treated as an override. "Ignore what I have, just test my project out with this config". You mentioned that there was a regression here though, so I wanted to check what the expected behavior was for your project

**Comment by jpsim** [comment]
Yes, for an explicit config passed as an argument, I'd also expect that to take precedence.

**Comment by sethfri** [comment]
Just had time to set up a repro for this. Using the sample project (out-of-tree config not included in the zip):

* **Before my change:** Out-of-tree config is used in place of the root config
* **After my change:** Out-of-tree config is _merged_ with root config

[SwiftLintBugTest.zip](https://github.com/realm/SwiftLint/files/5360699/SwiftLintBugTest.zip)

Will see if I can figure out how to fix this, but is this consistent with what you were seeing @jpsim?

**Comment by jpsim** [comment]
That sounds like what I was seeing, yes. Thanks for taking the time to do this!

**Comment by sethfri** [comment]
@jpsim Np! Opened a PR with a fix in #3379

**Pull request merged**
