### PR TITLE
Generate Swift Syntax Dashboard in documentation

### PR DESCRIPTION
**Pull request by jpsim**
This is a useful overview of where the migration effort stands and what rules can be migrated next.

image

### CODE REVIEW

**Comment by jpsim** [comment]
FYI @marcelofabri @SimplyDanny since you've been doing the bulk of the migrations

**Comment by marcelofabri** [comment]
Nice! Can we group by default x opt-in rules as well? I’ve been trying to focus on riles where the impact would be greater

**Comment by jpsim** [comment]
> Nice! Can we group by default x opt-in rules as well? I’ve been trying to focus on riles where the impact would be greater

thanks for the suggestion, I was considering doing that, so now you’ve convinced me!

**Comment by jpsim** [comment]
Published here: https://realm.github.io/SwiftLint/swift-syntax-dashboard.html

**Pull request merged**
