### PR TITLE
Add option to pass successfully if no files passed to SwiftLint are lintable

### PR DESCRIPTION
**Pull request by thedavidharris**
Addresses https://github.com/realm/SwiftLint/issues/2608.

### CODE REVIEW

**Comment by dharr419-ford** [comment]
Opening this up for review; if this is worth an integration test can add, but that seems to be the only way to test this the way things are structured

**Comment by thedavidharris** [comment]
Not totally sure the best way to add tests to this, since it appears that most config-level things are integration tested and I'm not sure I want to mess with those just to test this early-exit case.

**Comment by jpsim** [comment]
Sorry for the delay in reviewing this @thedavidharris. Instead of compiler arguments, could this be done as a Configuration file setting? My reasoning is that I believe well-configured projects with no violations should pass with a plain `swiftlint` invocation.

You can look at several of the other top-level keys in [Configuration+Parsing.swift](https://github.com/realm/SwiftLint/blob/0.38.1/Source/SwiftLintFramework/Extensions/Configuration+Parsing.swift#L9) for examples of how to wire them in.

**Comment by thedavidharris** [comment]
@jpsim yep makes sense, will have a go at it this week

**Comment by thedavidharris** [comment]
Should be all updated now with the right docs and as a config param

**Comment by Fab1n** [comment]
Is there a reason why this flag is documented nowhere and you need to really dig in to find out that this option exists?
@thedavidharris

**Comment by vakhidbetrakhmadov** [comment]
Hi, `allow_zero_lintable_files: true` doesn't work when added to a parent config that's loaded by a child config.
It only work if `allow_zero_lintable_files: true` is specified in the child config.
Is this is a know issue ?

https://github.com/realm/SwiftLint/issues/6240

**Pull request merged**
